#pragma once
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "constants.h"
#include "utils.h"

// Global lookup table for instructions
// (prefix, opcode) -> (reg -> operator)
const std::unordered_map<std::pair<Prefix, int>,
                         std::unordered_map<int, Mnemonic>>
    OP_LOOKUP = {{{Prefix::NONE, u2d("\x05")}, {{-1, Mnemonic::ADD}}},
                 {{Prefix::NONE, u2d("\x81")}, {{u2d("\x00"), Mnemonic::ADD}}},
                 {{Prefix::NONE, u2d("\x83")}, {{u2d("\x00"), Mnemonic::ADD}}},
                 {{Prefix::NONE, u2d("\x01")}, {{-1, Mnemonic::ADD}}},
                 {{Prefix::NONE, u2d("\x03")}, {{-1, Mnemonic::ADD}}}};

// Lookup table for operand information
// (prefix, operator, opcode) -> (encoding, remaining opecodes, operands)
const std::unordered_map<
    std::tuple<Prefix, Mnemonic, int>,
    std::tuple<OpEnc, std::vector<std::string>, std::vector<Operand>>>
    OPERAND_LOOKUP = {
        // ADD
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x05")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x05")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x01")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x01")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x03")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x03")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // ADC
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x15")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x15")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x11")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x11")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x13")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x13")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // SUB
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x2D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x2D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x29")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x20")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x2B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x2B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // SBB
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x1D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x1D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x19")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x19")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x1B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x1B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // INC
        {{Prefix::NONE, Mnemonic::INC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::REX, Mnemonic::INC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::NONE, Mnemonic::INC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::REXW, Mnemonic::INC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm}}},
        // DEC
        {{Prefix::NONE, Mnemonic::DEC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::REX, Mnemonic::DEC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::NONE, Mnemonic::DEC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::REXW, Mnemonic::DEC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm}}},
        // NEG
        {{Prefix::NONE, Mnemonic::NEG, u2d("\xF6")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::REX, Mnemonic::NEG, u2d("\xF6")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::NONE, Mnemonic::NEG, u2d("\xF7")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::REXW, Mnemonic::NEG, u2d("\xF7")},
         {OpEnc::M, {}, {Operand::rm}}},
        // AND
        {{Prefix::P66, Mnemonic::AND, u2d("\x25")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x25")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x25")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x21")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x21")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x21")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x23")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x23")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x23")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // OR
        {{Prefix::P66, Mnemonic::OR, u2d("\x0D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x0D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x0D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x09")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x09")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x09")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x08")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x08")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x08")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // XOR
        {{Prefix::P66, Mnemonic::XOR, u2d("\x35")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x35")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x35")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x31")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x31")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x31")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x33")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x33")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x33")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // NOT
        {{Prefix::NONE, Mnemonic::NOT, u2d("\xF6")},
         {OpEnc::RM, {}, {Operand::reg}}},
        {{Prefix::REX, Mnemonic::NOT, u2d("\xF6")},
         {OpEnc::RM, {}, {Operand::reg}}},
        {{Prefix::P66, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg}}},
        {{Prefix::NONE, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg}}},
        {{Prefix::REXW, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg}}},
        // MUL
        {{Prefix::NONE, Mnemonic::NOT, u2d("\xF6")},
         {OpEnc::RM, {}, {Operand::reg}}},
        {{Prefix::REX, Mnemonic::NOT, u2d("\xF6")},
         {OpEnc::RM, {}, {Operand::reg}}},
        {{Prefix::P66, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg}}},
        {{Prefix::NONE, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg}}},
        {{Prefix::REXW, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg}}},
        // IMUL
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\xF6")},
         {OpEnc::MR, {"/r"}, {Operand::ax, Operand::rm}}},
        {{Prefix::REX, Mnemonic::IMUL, u2d("\xF6")},
         {OpEnc::MR, {"/r"}, {Operand::ax, Operand::rm}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\xF7")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::rm}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\xF7")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\xF7")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::rm}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x0F\xAF")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x0F\xAF")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x0F\xAF")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg, Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg, Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg, Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"iw"}, {Operand::reg, Operand::rm, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"id"}, {Operand::reg, Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"id"}, {Operand::reg, Operand::rm, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"iw"}, {Operand::reg, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"id"}, {Operand::reg, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"id"}, {Operand::reg, Operand::imm32}}},
        // DIV
        {{Prefix::NONE, Mnemonic::DIV, u2d("\xF6")},
         {OpEnc::M, {"/r"}, {Operand::rm}}},
        {{Prefix::REX, Mnemonic::DIV, u2d("\xF6")},
         {OpEnc::M, {"/r"}, {Operand::rm}}},
        {{Prefix::P66, Mnemonic::DIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm}}},
        {{Prefix::NONE, Mnemonic::DIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm}}},
        {{Prefix::REXW, Mnemonic::DIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm}}},
        // IDIV
        {{Prefix::NONE, Mnemonic::IDIV, u2d("\xF6")},
         {OpEnc::M, {"/r"}, {Operand::rm}}},
        {{Prefix::REX, Mnemonic::IDIV, u2d("\xF6")},
         {OpEnc::M, {"/r"}, {Operand::rm}}},
        {{Prefix::P66, Mnemonic::IDIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm}}},
        {{Prefix::NONE, Mnemonic::IDIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm}}},
        {{Prefix::REXW, Mnemonic::IDIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm}}},
        // CMP
        {{Prefix::P66, Mnemonic::CMP, u2d("\x3D")},
         {OpEnc::I, {"id"}, {Operand::ax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x3D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x3D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::CMP, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::CMP, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::CMP, u2d("\x39")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x39")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x39")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::P66, Mnemonic::CMP, u2d("\x3B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x3B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x3B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // TEST
        {{Prefix::NONE, Mnemonic::TEST, u2d("\xA8")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::TEST, u2d("\xA9")},
         {OpEnc::I, {"iw"}, {Operand::ax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\xA9")},
         {OpEnc::I, {"id"}, {Operand::ax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::TEST, u2d("\xA9")},
         {OpEnc::I, {"id"}, {Operand::ax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\xF6")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::TEST, u2d("\xF6")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::TEST, u2d("\xF7")},
         {OpEnc::MI, {"iw"}, {Operand::rm, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\xF7")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::TEST, u2d("\xF7")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\x84")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REX, Mnemonic::TEST, u2d("\x84")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::P66, Mnemonic::TEST, u2d("\x85")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\x85")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::TEST, u2d("\x85")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        // MOV
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x88")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\x88")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\x89")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x89")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\x89")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x8A")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\x8A")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\x8B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x8B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\x8B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x8C")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\x8C")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x8E")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\x8E")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xA0")},
         {OpEnc::M, {}, {Operand::al, Operand::moff}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xA0")},
         {OpEnc::M, {}, {Operand::al, Operand::moff}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xA1")},
         {OpEnc::M, {}, {Operand::ax, Operand::moff}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xA1")},
         {OpEnc::M, {}, {Operand::eax, Operand::moff}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xA1")},
         {OpEnc::M, {}, {Operand::rax, Operand::moff}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xA2")},
         {OpEnc::M, {}, {Operand::moff, Operand::al}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xA2")},
         {OpEnc::M, {}, {Operand::moff, Operand::al}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xA3")},
         {OpEnc::M, {}, {Operand::moff, Operand::ax}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xA3")},
         {OpEnc::M, {}, {Operand::moff, Operand::rax}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB0")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB0")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB1")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB1")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB2")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB2")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB3")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB3")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB4")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB4")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB5")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB5")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB6")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB6")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB7")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB7")},
         {OpEnc::I, {"rb"}, {Operand::reg, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xB8")},
         {OpEnc::I, {"rw"}, {Operand::reg, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB8")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xB8")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xB9")},
         {OpEnc::I, {"rw"}, {Operand::reg, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB9")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xB9")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBA")},
         {OpEnc::I, {"rw"}, {Operand::reg, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBA")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBA")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBB")},
         {OpEnc::I, {"rw"}, {Operand::reg, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBB")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBB")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBC")},
         {OpEnc::I, {"rw"}, {Operand::reg, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBC")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBC")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBD")},
         {OpEnc::I, {"rw"}, {Operand::reg, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBD")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBD")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBE")},
         {OpEnc::I, {"rw"}, {Operand::reg, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBE")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBE")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBF")},
         {OpEnc::I, {"rw"}, {Operand::reg, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBF")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBF")},
         {OpEnc::I, {"rd"}, {Operand::reg, Operand::imm64}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xC6")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xC6")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xC7")},
         {OpEnc::MI, {"iw"}, {Operand::rm, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xC7")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xC7")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
};

// Supported operators set
const std::unordered_set<std::string> SUPPORTED_OPERATORS;
