#pragma once
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "constants.h"
#include "utils.h"

// Global lookup table for instructions
// (prefix, opcode) -> (reg -> operator)
const std::unordered_map<std::pair<Prefix, int>,
                         std::unordered_map<int, Mnemonic>>
    OP_LOOKUP = {{{Prefix::NONE, u2d("\x05")}, {{-1, Mnemonic::ADD}}},
                 {{Prefix::NONE, u2d("\x81")}, {{u2d("\x00"), Mnemonic::ADD}}},
                 {{Prefix::NONE, u2d("\x83")}, {{u2d("\x00"), Mnemonic::ADD}}},
                 {{Prefix::NONE, u2d("\x01")}, {{-1, Mnemonic::ADD}}},
                 {{Prefix::NONE, u2d("\x03")}, {{-1, Mnemonic::ADD}}}};

// Lookup table for operand information
// (prefix, operator, opcode) -> (encoding, remaining opecodes, operands)
const std::unordered_map<
    std::tuple<Prefix, Mnemonic, int>,
    std::tuple<OpEnc, std::vector<std::string>, std::vector<Operand>>>
    OPERAND_LOOKUP = {
        // ADD
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x05")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x05")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x01")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x01")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x03")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x03")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // ADC
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x15")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x15")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x11")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x11")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x13")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x13")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // SUB
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x2D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x2D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x29")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x20")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x2B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x2B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // SBB
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x1D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x1D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x19")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x19")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x1B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x1B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // INC
        {{Prefix::NONE, Mnemonic::INC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::REX, Mnemonic::INC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::NONE, Mnemonic::INC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::REXW, Mnemonic::INC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm}}},
        // DEC
        {{Prefix::NONE, Mnemonic::DEC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::REX, Mnemonic::DEC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::NONE, Mnemonic::DEC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::REXW, Mnemonic::DEC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm}}},
        // NEG
        {{Prefix::NONE, Mnemonic::NEG, u2d("\xF6")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::REX, Mnemonic::NEG, u2d("\xF6")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::NONE, Mnemonic::NEG, u2d("\xF7")},
         {OpEnc::M, {}, {Operand::rm}}},
        {{Prefix::REXW, Mnemonic::NEG, u2d("\xF7")},
         {OpEnc::M, {}, {Operand::rm}}},
        // AND
        {{Prefix::P66, Mnemonic::AND, u2d("\x25")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x25")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x25")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x21")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x21")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x21")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x23")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x23")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x23")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // OR
        {{Prefix::P66, Mnemonic::OR, u2d("\x0D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x0D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x0D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x09")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x09")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x09")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x08")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x08")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x08")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // XOR
        {{Prefix::P66, Mnemonic::XOR, u2d("\x35")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x35")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x35")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x31")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x31")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x31")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x33")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x33")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x33")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
        // CMP
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x3D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x39")},
         {OpEnc::MR, {"/r"}, {Operand::rm, Operand::reg}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x3B")},
         {OpEnc::RM, {"/r"}, {Operand::reg, Operand::rm}}},
};

// Supported operators set
const std::unordered_set<std::string> SUPPORTED_OPERATORS;
