// SBB
{{Prefix::NONE, Mnemonic::SBB, u2d("\x1C")},
 {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
    {{Prefix::NONE, Mnemonic::SBB, u2d("\x1D")},
     {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
    {{Prefix::REXW, Mnemonic::SBB, u2d("\x1D")},
     {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
    {{Prefix::NONE, Mnemonic::SBB, u2d("\x80")},
     {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
    {{Prefix::REX, Mnemonic::SBB, u2d("\x80")},
     {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
    {{Prefix::NONE, Mnemonic::SBB, u2d("\x81")},
     {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
    {{Prefix::REXW, Mnemonic::SBB, u2d("\x81")},
     {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
    {{Prefix::NONE, Mnemonic::SBB, u2d("\x83")},
     {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
    {{Prefix::REXW, Mnemonic::SBB, u2d("\x83")},
     {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
    {{Prefix::NONE, Mnemonic::SBB, u2d("\x19")},
     {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
    {{Prefix::REXW, Mnemonic::SBB, u2d("\x19")},
     {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
    {{Prefix::NONE, Mnemonic::SBB, u2d("\x1A")},
     {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
    {{Prefix::REX, Mnemonic::SBB, u2d("\x1A")},
     {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
    {{Prefix::NONE, Mnemonic::SBB, u2d("\x1B")},
     {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
    {{Prefix::REXW, Mnemonic::SBB, u2d("\x1B")},
     {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},