#pragma once
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "constants.h"
#include "utils.h"

// Global lookup table for instructions
// (prefix, opcode) -> (reg -> operator)
const std::unordered_map<std::pair<Prefix, int>,
                         std::unordered_map<int, Mnemonic>>
    OP_LOOKUP = {
        // SETNE
        {{Prefix::NONE, u2d("\x0F\x95")}, {{-1, Mnemonic::SETNE}}},
        {{Prefix::REX, u2d("\x0F\x95")}, {{-1, Mnemonic::SETNE}}},

        // FADD
        {{Prefix::NONE, u2d("\xD8")}, {{0, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xDC")}, {{0, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xD8\xC0")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xD8\xC1")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xD8\xC2")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xD8\xC3")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xD8\xC4")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xD8\xC5")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xD8\xC6")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xD8\xC7")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xDC\xC0")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xDC\xC1")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xDC\xC2")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xDC\xC3")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xDC\xC4")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xDC\xC5")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xDC\xC6")}, {{-1, Mnemonic::FADD}}},
        {{Prefix::NONE, u2d("\xDC\xC7")}, {{-1, Mnemonic::FADD}}},

        // FXCH
        {{Prefix::NONE, u2d("\xD9\xC8")}, {{-1, Mnemonic::FXCH}}},
        {{Prefix::NONE, u2d("\xD9\xC9")}, {{-1, Mnemonic::FXCH}}},
        {{Prefix::NONE, u2d("\xD9\xCA")}, {{-1, Mnemonic::FXCH}}},
        {{Prefix::NONE, u2d("\xD9\xCB")}, {{-1, Mnemonic::FXCH}}},
        {{Prefix::NONE, u2d("\xD9\xCC")}, {{-1, Mnemonic::FXCH}}},
        {{Prefix::NONE, u2d("\xD9\xCD")}, {{-1, Mnemonic::FXCH}}},
        {{Prefix::NONE, u2d("\xD9\xCE")}, {{-1, Mnemonic::FXCH}}},
        {{Prefix::NONE, u2d("\xD9\xCF")}, {{-1, Mnemonic::FXCH}}},

        // CMOVE
        {{Prefix::NONE, u2d("\x0F\x44")}, {{-1, Mnemonic::CMOVE}}},

        // MOVAPS
        {{Prefix::NONE, u2d("\x0F\x28")}, {{-1, Mnemonic::MOVAPS}}},
        {{Prefix::NONE, u2d("\x0F\x29")}, {{-1, Mnemonic::MOVAPS}}},

        // ENDBR
        {{Prefix::NONE, u2d("\xF3\x0F\x1E\xFA")}, {{-1, Mnemonic::ENDBR64}}},
        {{Prefix::NONE, u2d("\xF3\x0F\x1E\xFB")}, {{-1, Mnemonic::ENDBR32}}},

        // IN
        {{Prefix::NONE, u2d("\xE4")}, {{-1, Mnemonic::IN}}},
        {{Prefix::NONE, u2d("\xE5")}, {{-1, Mnemonic::IN}}},
        {{Prefix::NONE, u2d("\xEC")}, {{-1, Mnemonic::IN}}},
        {{Prefix::NONE, u2d("\xED")}, {{-1, Mnemonic::IN}}},

        // OUT
        {{Prefix::NONE, u2d("\xE6")}, {{-1, Mnemonic::OUT}}},
        {{Prefix::NONE, u2d("\xE7")}, {{-1, Mnemonic::OUT}}},
        {{Prefix::NONE, u2d("\xEE")}, {{-1, Mnemonic::OUT}}},
        {{Prefix::NONE, u2d("\xEF")}, {{-1, Mnemonic::OUT}}},

        // LOOP
        {{Prefix::NONE, u2d("\xE2")}, {{-1, Mnemonic::LOOP}}},
        {{Prefix::NONE, u2d("\xE1")}, {{-1, Mnemonic::LOOPE}}},
        {{Prefix::NONE, u2d("\xE0")}, {{-1, Mnemonic::LOOPNE}}},

        {{Prefix::NONE, u2d("\xE3")}, {{-1, Mnemonic::JECXZ}}},
        {{Prefix::NONE, u2d("\x6C")}, {{-1, Mnemonic::INSB}}},
        {{Prefix::NONE, u2d("\x6D")}, {{-1, Mnemonic::INSW}}},
        {{Prefix::NONE, u2d("\x6E")}, {{-1, Mnemonic::OUTSB}}},
        {{Prefix::NONE, u2d("\x6F")}, {{-1, Mnemonic::OUTSW}}},
        {{Prefix::NONE, u2d("\xAE")}, {{-1, Mnemonic::SCASB}}},
        {{Prefix::NONE, u2d("\xAF")}, {{-1, Mnemonic::SCASW}}},
        {{Prefix::REXW, u2d("\xAF")}, {{-1, Mnemonic::SCASQ}}},
        {{Prefix::NONE, u2d("\xAA")}, {{-1, Mnemonic::STOSB}}},
        {{Prefix::NONE, u2d("\xAB")}, {{-1, Mnemonic::STOSW}}},
        {{Prefix::REXW, u2d("\xAB")}, {{-1, Mnemonic::STOSQ}}},
        {{Prefix::NONE, u2d("\xAC")}, {{-1, Mnemonic::LODSB}}},
        {{Prefix::NONE, u2d("\xAD")}, {{-1, Mnemonic::LODSW}}},
        {{Prefix::REXW, u2d("\xAD")}, {{-1, Mnemonic::LODSQ}}},
        {{Prefix::NONE, u2d("\xA4")}, {{-1, Mnemonic::MOVSB}}},
        {{Prefix::NONE, u2d("\xA5")}, {{-1, Mnemonic::MOVSW}}},
        {{Prefix::REXW, u2d("\xA5")}, {{-1, Mnemonic::MOVSQ}}},
        {{Prefix::NONE, u2d("\xA6")}, {{-1, Mnemonic::CMPSB}}},
        {{Prefix::NONE, u2d("\xA7")}, {{-1, Mnemonic::CMPSW}}},
        {{Prefix::REXW, u2d("\xA7")}, {{-1, Mnemonic::CMPSQ}}},
        {{Prefix::NONE, u2d("\xC9")}, {{-1, Mnemonic::LEAVE}}},
        {{Prefix::NONE, u2d("\x0F\xA2")}, {{-1, Mnemonic::CPUID}}},
        {{Prefix::NONE, u2d("\xF8")}, {{-1, Mnemonic::CLC}}},
        {{Prefix::NONE, u2d("\xFC")}, {{-1, Mnemonic::CLD}}},
        {{Prefix::NONE, u2d("\xF9")}, {{-1, Mnemonic::STC}}},

        // ADD, ADC, SUB, SBB, AND, OR, XOR, CMP
        {{Prefix::NONE, u2d("\x04")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::NONE, u2d("\x14")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::NONE, u2d("\x2C")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::NONE, u2d("\x1C")}, {{-1, Mnemonic::SBB}}},

        {{Prefix::NONE, u2d("\x24")}, {{-1, Mnemonic::AND}}},
        {{Prefix::NONE, u2d("\x0C")}, {{-1, Mnemonic::OR}}},
        {{Prefix::NONE, u2d("\x34")}, {{-1, Mnemonic::XOR}}},

        {{Prefix::NONE, u2d("\x3C")}, {{-1, Mnemonic::CMP}}},
        {{Prefix::NONE, u2d("\x3D")}, {{-1, Mnemonic::CMP}}},
        {{Prefix::REXW, u2d("\x3D")}, {{-1, Mnemonic::CMP}}},
        {{Prefix::NONE, u2d("\x38")}, {{-1, Mnemonic::CMP}}},
        {{Prefix::REX, u2d("\x38")}, {{-1, Mnemonic::CMP}}},
        {{Prefix::NONE, u2d("\x39")}, {{-1, Mnemonic::CMP}}},
        {{Prefix::REXW, u2d("\x39")}, {{-1, Mnemonic::CMP}}},
        {{Prefix::NONE, u2d("\x3A")}, {{-1, Mnemonic::CMP}}},
        {{Prefix::REX, u2d("\x3A")}, {{-1, Mnemonic::CMP}}},
        {{Prefix::NONE, u2d("\x3B")}, {{-1, Mnemonic::CMP}}},
        {{Prefix::REXW, u2d("\x3B")}, {{-1, Mnemonic::CMP}}},

        {{Prefix::NONE, u2d("\x05")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::REXW, u2d("\x05")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::NONE, u2d("\x15")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::REXW, u2d("\x15")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::NONE, u2d("\x2D")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::REXW, u2d("\x2D")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::NONE, u2d("\x1D")}, {{-1, Mnemonic::SBB}}},
        {{Prefix::REXW, u2d("\x1D")}, {{-1, Mnemonic::SBB}}},

        {{Prefix::NONE, u2d("\x25")}, {{-1, Mnemonic::AND}}},
        {{Prefix::REXW, u2d("\x25")}, {{-1, Mnemonic::AND}}},
        {{Prefix::P66, u2d("\x25")}, {{-1, Mnemonic::AND}}},
        {{Prefix::NONE, u2d("\x0D")}, {{-1, Mnemonic::OR}}},
        {{Prefix::REXW, u2d("\x0D")}, {{-1, Mnemonic::OR}}},
        {{Prefix::P66, u2d("\x0D")}, {{-1, Mnemonic::OR}}},
        {{Prefix::NONE, u2d("\x35")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::REXW, u2d("\x35")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::P66, u2d("\x35")}, {{-1, Mnemonic::XOR}}},

        {{Prefix::NONE, u2d("\x80")},
         {{0, Mnemonic::ADD},
          {2, Mnemonic::ADC},
          {5, Mnemonic::SUB},
          {3, Mnemonic::SBB},
          {4, Mnemonic::AND},
          {1, Mnemonic::OR},
          {6, Mnemonic::XOR},
          {7, Mnemonic::CMP}}},
        {{Prefix::REX, u2d("\x80")},
         {{0, Mnemonic::ADD},
          {2, Mnemonic::ADC},
          {5, Mnemonic::SUB},
          {3, Mnemonic::SBB},
          {4, Mnemonic::AND},
          {1, Mnemonic::OR},
          {6, Mnemonic::XOR},
          {7, Mnemonic::CMP}}},

        {{Prefix::NONE, u2d("\x81")},
         {{0, Mnemonic::ADD},
          {2, Mnemonic::ADC},
          {5, Mnemonic::SUB},
          {3, Mnemonic::SBB},
          {4, Mnemonic::AND},
          {1, Mnemonic::OR},
          {6, Mnemonic::XOR},
          {7, Mnemonic::CMP}}},
        {{Prefix::REXW, u2d("\x81")},
         {{0, Mnemonic::ADD},
          {2, Mnemonic::ADC},
          {5, Mnemonic::SUB},
          {3, Mnemonic::SBB},
          {4, Mnemonic::AND},
          {1, Mnemonic::OR},
          {6, Mnemonic::XOR},
          {7, Mnemonic::CMP}}},

        {{Prefix::NONE, u2d("\x83")},
         {{0, Mnemonic::ADD},
          {2, Mnemonic::ADC},
          {5, Mnemonic::SUB},
          {3, Mnemonic::SBB},
          {4, Mnemonic::AND},
          {1, Mnemonic::OR},
          {6, Mnemonic::XOR},
          {7, Mnemonic::CMP}}},
        {{Prefix::REXW, u2d("\x83")},
         {{0, Mnemonic::ADD},
          {2, Mnemonic::ADC},
          {5, Mnemonic::SUB},
          {3, Mnemonic::SBB},
          {4, Mnemonic::AND},
          {1, Mnemonic::OR},
          {6, Mnemonic::XOR},
          {7, Mnemonic::CMP}}},

        {{Prefix::NONE, u2d("\x00")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::REX, u2d("\x00")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::NONE, u2d("\x10")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::REX, u2d("\x10")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::NONE, u2d("\x28")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::REX, u2d("\x28")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::NONE, u2d("\x18")}, {{-1, Mnemonic::SBB}}},
        {{Prefix::REX, u2d("\x18")}, {{-1, Mnemonic::SBB}}},
        {{Prefix::NONE, u2d("\x20")}, {{-1, Mnemonic::AND}}},
        {{Prefix::REX, u2d("\x20")}, {{-1, Mnemonic::AND}}},
        {{Prefix::NONE, u2d("\x08")}, {{-1, Mnemonic::OR}}},
        {{Prefix::REX, u2d("\x08")}, {{-1, Mnemonic::OR}}},
        {{Prefix::NONE, u2d("\x30")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::REX, u2d("\x30")}, {{-1, Mnemonic::XOR}}},

        {{Prefix::NONE, u2d("\x01")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::REXW, u2d("\x01")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::NONE, u2d("\x11")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::REXW, u2d("\x11")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::NONE, u2d("\x29")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::REXW, u2d("\x29")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::NONE, u2d("\x19")}, {{-1, Mnemonic::SBB}}},
        {{Prefix::REXW, u2d("\x19")}, {{-1, Mnemonic::SBB}}},

        {{Prefix::NONE, u2d("\x20")}, {{-1, Mnemonic::AND}}},
        {{Prefix::REXW, u2d("\x20")}, {{-1, Mnemonic::AND}}},
        {{Prefix::P66, u2d("\x20")}, {{-1, Mnemonic::AND}}},
        {{Prefix::NONE, u2d("\x08")}, {{-1, Mnemonic::OR}}},
        {{Prefix::REXW, u2d("\x08")}, {{-1, Mnemonic::OR}}},
        {{Prefix::P66, u2d("\x08")}, {{-1, Mnemonic::OR}}},
        {{Prefix::NONE, u2d("\x30")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::REXW, u2d("\x30")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::P66, u2d("\x30")}, {{-1, Mnemonic::XOR}}},

        {{Prefix::NONE, u2d("\x02")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::REX, u2d("\x02")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::NONE, u2d("\x12")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::REX, u2d("\x12")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::NONE, u2d("\x2A")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::REX, u2d("\x2A")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::NONE, u2d("\x1A")}, {{-1, Mnemonic::SBB}}},
        {{Prefix::REX, u2d("\x1A")}, {{-1, Mnemonic::SBB}}},

        {{Prefix::NONE, u2d("\x21")}, {{-1, Mnemonic::AND}}},
        {{Prefix::REXW, u2d("\x21")}, {{-1, Mnemonic::AND}}},
        {{Prefix::P66, u2d("\x21")}, {{-1, Mnemonic::AND}}},
        {{Prefix::NONE, u2d("\x09")}, {{-1, Mnemonic::OR}}},
        {{Prefix::REXW, u2d("\x09")}, {{-1, Mnemonic::OR}}},
        {{Prefix::P66, u2d("\x09")}, {{-1, Mnemonic::OR}}},
        {{Prefix::NONE, u2d("\x31")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::REXW, u2d("\x31")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::P66, u2d("\x31")}, {{-1, Mnemonic::XOR}}},

        {{Prefix::NONE, u2d("\x03")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::REXW, u2d("\x03")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::NONE, u2d("\x13")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::REXW, u2d("\x13")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::NONE, u2d("\x2B")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::REXW, u2d("\x2B")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::NONE, u2d("\x1B")}, {{-1, Mnemonic::SBB}}},
        {{Prefix::REXW, u2d("\x1B")}, {{-1, Mnemonic::SBB}}},

        {{Prefix::NONE, u2d("\x22")}, {{-1, Mnemonic::AND}}},
        {{Prefix::REX, u2d("\x22")}, {{-1, Mnemonic::AND}}},
        {{Prefix::NONE, u2d("\x0A")}, {{-1, Mnemonic::OR}}},
        {{Prefix::REX, u2d("\x0A")}, {{-1, Mnemonic::OR}}},
        {{Prefix::NONE, u2d("\x32")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::REX, u2d("\x32")}, {{-1, Mnemonic::XOR}}},

        {{Prefix::NONE, u2d("\x23")}, {{-1, Mnemonic::AND}}},
        {{Prefix::REXW, u2d("\x23")}, {{-1, Mnemonic::AND}}},
        {{Prefix::P66, u2d("\x23")}, {{-1, Mnemonic::AND}}},
        {{Prefix::NONE, u2d("\x0B")}, {{-1, Mnemonic::OR}}},
        {{Prefix::REXW, u2d("\x0B")}, {{-1, Mnemonic::OR}}},
        {{Prefix::P66, u2d("\x0B")}, {{-1, Mnemonic::OR}}},
        {{Prefix::NONE, u2d("\x33")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::REXW, u2d("\x33")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::P66, u2d("\x33")}, {{-1, Mnemonic::XOR}}},

        // MOV
        {{Prefix::NONE, u2d("\x88")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\x88")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::P66, u2d("\x89")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\x89")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\x89")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::NONE, u2d("\x8A")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\x8A")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::P66, u2d("\x8B")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\x8B")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\x8B")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::NONE, u2d("\x8C")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\x8C")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::NONE, u2d("\x8E")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\x8E")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::NONE, u2d("\xA0")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xA0")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::P66, u2d("\xA1")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xA1")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xA1")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::NONE, u2d("\xA2")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xA2")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::NONE, u2d("\xA3")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xA3")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::NONE, u2d("\xB0")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB0")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB1")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB1")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB2")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB2")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB3")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB3")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB4")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB4")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB5")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB5")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB6")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB6")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB7")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB7")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::P66, u2d("\xB8")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB8")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xB8")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xB9")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB9")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xB9")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xBA")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xBA")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xBA")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xBB")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xBB")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xBB")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xBC")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xBC")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xBC")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xBD")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xBD")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xBD")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xBE")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xBE")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xBE")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xBF")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xBF")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xBF")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xC6")}, {{0, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xC6")}, {{0, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xC7")}, {{0, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xC7")}, {{0, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xC7")}, {{0, Mnemonic::MOV}}},

        // NEG, NOT, MUL, IMUL, DIV, IDIV, TEST
        {{Prefix::NONE, u2d("\xF6")},
         {{3, Mnemonic::NEG},
          {2, Mnemonic::NOT},
          {4, Mnemonic::MUL},
          {5, Mnemonic::IMUL},
          {6, Mnemonic::DIV},
          {7, Mnemonic::IDIV},
          {0, Mnemonic::TEST}}},
        {{Prefix::REX, u2d("\xF6")},
         {{3, Mnemonic::NEG},
          {2, Mnemonic::NOT},
          {4, Mnemonic::MUL},
          {5, Mnemonic::IMUL},
          {6, Mnemonic::DIV},
          {7, Mnemonic::IDIV},
          {0, Mnemonic::TEST}}},

        {{Prefix::P66, u2d("\xF7")},
         {{2, Mnemonic::NOT},
          {4, Mnemonic::MUL},
          {5, Mnemonic::IMUL},
          {6, Mnemonic::DIV},
          {7, Mnemonic::IDIV},
          {0, Mnemonic::TEST}}},
        {{Prefix::NONE, u2d("\xF7")},
         {{3, Mnemonic::NEG},
          {2, Mnemonic::NOT},
          {4, Mnemonic::MUL},
          {5, Mnemonic::IMUL},
          {6, Mnemonic::DIV},
          {7, Mnemonic::IDIV},
          {0, Mnemonic::TEST}}},
        {{Prefix::REXW, u2d("\xF7")},
         {{3, Mnemonic::NEG},
          {2, Mnemonic::NOT},
          {4, Mnemonic::MUL},
          {5, Mnemonic::IMUL},
          {6, Mnemonic::DIV},
          {7, Mnemonic::IDIV},
          {0, Mnemonic::TEST}}},

        {{Prefix::NONE, u2d("\x84")}, {{-1, Mnemonic::TEST}}},
        {{Prefix::REX, u2d("\x84")}, {{-1, Mnemonic::TEST}}},
        {{Prefix::NONE, u2d("\x85")}, {{-1, Mnemonic::TEST}}},
        {{Prefix::REXW, u2d("\x85")}, {{-1, Mnemonic::TEST}}},

        {{Prefix::P66, u2d("\x0F\xAF")}, {{-1, Mnemonic::IMUL}}},
        {{Prefix::NONE, u2d("\x0F\xAF")}, {{-1, Mnemonic::IMUL}}},
        {{Prefix::REXW, u2d("\x0F\xAF")}, {{-1, Mnemonic::IMUL}}},

        {{Prefix::P66, u2d("\x6B")}, {{-1, Mnemonic::IMUL}}},
        {{Prefix::NONE, u2d("\x6B")}, {{-1, Mnemonic::IMUL}}},
        {{Prefix::REXW, u2d("\x6B")}, {{-1, Mnemonic::IMUL}}},

        {{Prefix::P66, u2d("\x69")}, {{-1, Mnemonic::IMUL}}},
        {{Prefix::NONE, u2d("\x69")}, {{-1, Mnemonic::IMUL}}},
        {{Prefix::REXW, u2d("\x69")}, {{-1, Mnemonic::IMUL}}},

        {{Prefix::NONE, u2d("\xA8")}, {{-1, Mnemonic::TEST}}},
        {{Prefix::P66, u2d("\xA9")}, {{-1, Mnemonic::TEST}}},
        {{Prefix::NONE, u2d("\xA9")}, {{-1, Mnemonic::TEST}}},
        {{Prefix::REXW, u2d("\xA9")}, {{-1, Mnemonic::TEST}}},

        // INC, DEC
        {{Prefix::NONE, u2d("\xFE")}, {{0, Mnemonic::INC}, {1, Mnemonic::DEC}}},
        {{Prefix::REX, u2d("\xFE")}, {{0, Mnemonic::INC}, {1, Mnemonic::DEC}}},
        {{Prefix::REXW, u2d("\xFE")}, {{0, Mnemonic::INC}, {1, Mnemonic::DEC}}},

        // CBW, CWDE, CDQE
        {{Prefix::P66, u2d("\x98")}, {{-1, Mnemonic::CBW}}},
        {{Prefix::NONE, u2d("\x98")}, {{-1, Mnemonic::CWDE}}},
        {{Prefix::REXW, u2d("\x98")}, {{-1, Mnemonic::CDQE}}},

        // CWD, CDQ, CQO
        {{Prefix::P66, u2d("\x98")}, {{-1, Mnemonic::CWD}}},
        {{Prefix::NONE, u2d("\x98")}, {{-1, Mnemonic::CDQ}}},
        {{Prefix::REXW, u2d("\x98")}, {{-1, Mnemonic::CQO}}},

        // MOVSX
        {{Prefix::P66, u2d("\x0F\xBE")}, {{-1, Mnemonic::MOVSX}}},
        {{Prefix::NONE, u2d("\x0F\xBE")}, {{-1, Mnemonic::MOVSX}}},
        {{Prefix::REX, u2d("\x0F\xBE")}, {{-1, Mnemonic::MOVSX}}},
        {{Prefix::NONE, u2d("\x0F\xBF")}, {{-1, Mnemonic::MOVSX}}},
        {{Prefix::REXW, u2d("\x0F\xBF")}, {{-1, Mnemonic::MOVSX}}},

        // MOVSXD
        {{Prefix::REXW, u2d("\x63")}, {{-1, Mnemonic::MOVSXD}}},

        // MOVZX
        {{Prefix::P66, u2d("\x0F\xB6")}, {{-1, Mnemonic::MOVZX}}},
        {{Prefix::NONE, u2d("\x0F\xB6")}, {{-1, Mnemonic::MOVZX}}},
        {{Prefix::REX, u2d("\x0F\xB6")}, {{-1, Mnemonic::MOVZX}}},
        {{Prefix::NONE, u2d("\x0F\xB7")}, {{-1, Mnemonic::MOVZX}}},
        {{Prefix::REXW, u2d("\x0F\xB7")}, {{-1, Mnemonic::MOVZX}}},

        // LEA
        {{Prefix::P66, u2d("\x8D")}, {{-1, Mnemonic::LEA}}},
        {{Prefix::NONE, u2d("\x8D")}, {{-1, Mnemonic::LEA}}},
        {{Prefix::REXW, u2d("\x8D")}, {{-1, Mnemonic::LEA}}},

        // NOP
        {{Prefix::NONE, u2d("\x90")}, {{-1, Mnemonic::NOP}}},
        {{Prefix::NONE, u2d("\x0F\x1F")}, {{0, Mnemonic::NOP}}},

        // RET
        {{Prefix::NONE, u2d("\xC3")}, {{-1, Mnemonic::RET}}},
        {{Prefix::NONE, u2d("\xCB")}, {{-1, Mnemonic::RET}}},
        {{Prefix::NONE, u2d("\xC2")}, {{-1, Mnemonic::RET}}},
        {{Prefix::NONE, u2d("\xCA")}, {{-1, Mnemonic::RET}}},

        {{Prefix::NONE, u2d("\xFF")},
         {{0, Mnemonic::INC},
          {1, Mnemonic::DEC},
          {2, Mnemonic::CALL},
          {4, Mnemonic::JMP},
          {5, Mnemonic::JMP},
          {6, Mnemonic::PUSH}}},

        // CALL
        {{Prefix::NONE, u2d("\xE8")}, {{-1, Mnemonic::CALL}}},
        {{Prefix::NONE, u2d("\x9A")}, {{-1, Mnemonic::CALL}}},

        // JCC
        {{Prefix::NONE, u2d("\x0F\x80")}, {{-1, Mnemonic::JO}}},
        {{Prefix::NONE, u2d("\x0F\x81")}, {{-1, Mnemonic::JNO}}},
        {{Prefix::NONE, u2d("\x0F\x82")}, {{-1, Mnemonic::JNAE}}},
        {{Prefix::NONE, u2d("\x0F\x83")}, {{-1, Mnemonic::JNB}}},
        {{Prefix::NONE, u2d("\x0F\x84")}, {{-1, Mnemonic::JZ}}},
        {{Prefix::NONE, u2d("\x0F\x85")}, {{-1, Mnemonic::JNZ}}},
        {{Prefix::NONE, u2d("\x0F\x86")}, {{-1, Mnemonic::JNA}}},
        {{Prefix::NONE, u2d("\x0F\x87")}, {{-1, Mnemonic::JNBE}}},
        {{Prefix::NONE, u2d("\x0F\x88")}, {{-1, Mnemonic::JS}}},
        {{Prefix::NONE, u2d("\x0F\x89")}, {{-1, Mnemonic::JNS}}},
        {{Prefix::NONE, u2d("\x0F\x8A")}, {{-1, Mnemonic::JP}}},
        {{Prefix::NONE, u2d("\x0F\x8B")}, {{-1, Mnemonic::JPO}}},
        {{Prefix::NONE, u2d("\x0F\x8C")}, {{-1, Mnemonic::JNGE}}},
        {{Prefix::NONE, u2d("\x0F\x8D")}, {{-1, Mnemonic::JNL}}},
        {{Prefix::NONE, u2d("\x0F\x8E")}, {{-1, Mnemonic::JNG}}},
        {{Prefix::NONE, u2d("\x0F\x8F")}, {{-1, Mnemonic::JNLE}}},

        {{Prefix::NONE, u2d("\x70")}, {{-1, Mnemonic::JO}}},
        {{Prefix::NONE, u2d("\x71")}, {{-1, Mnemonic::JNO}}},
        {{Prefix::NONE, u2d("\x72")}, {{-1, Mnemonic::JNAE}}},
        {{Prefix::NONE, u2d("\x73")}, {{-1, Mnemonic::JNB}}},
        {{Prefix::NONE, u2d("\x74")}, {{-1, Mnemonic::JZ}}},
        {{Prefix::NONE, u2d("\x75")}, {{-1, Mnemonic::JNZ}}},
        {{Prefix::NONE, u2d("\x76")}, {{-1, Mnemonic::JNA}}},
        {{Prefix::NONE, u2d("\x77")}, {{-1, Mnemonic::JNBE}}},
        {{Prefix::NONE, u2d("\x78")}, {{-1, Mnemonic::JS}}},
        {{Prefix::NONE, u2d("\x79")}, {{-1, Mnemonic::JNS}}},
        {{Prefix::NONE, u2d("\x7A")}, {{-1, Mnemonic::JP}}},
        {{Prefix::NONE, u2d("\x7B")}, {{-1, Mnemonic::JPO}}},
        {{Prefix::NONE, u2d("\x7C")}, {{-1, Mnemonic::JNGE}}},
        {{Prefix::NONE, u2d("\x7D")}, {{-1, Mnemonic::JNL}}},
        {{Prefix::NONE, u2d("\x7E")}, {{-1, Mnemonic::JNG}}},
        {{Prefix::NONE, u2d("\x7F")}, {{-1, Mnemonic::JNLE}}},

        // JMP
        {{Prefix::NONE, u2d("\xEB")}, {{-1, Mnemonic::JMP}}},
        {{Prefix::NONE, u2d("\xE9")}, {{-1, Mnemonic::JMP}}},

        // BSWAP
        {{Prefix::NONE, u2d("\x0F\xC8")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::REXW, u2d("\x0F\xC8")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::NONE, u2d("\x0F\xC9")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::REXW, u2d("\x0F\xC9")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::NONE, u2d("\x0F\xCA")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::REXW, u2d("\x0F\xCA")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::NONE, u2d("\x0F\xCB")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::REXW, u2d("\x0F\xCB")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::NONE, u2d("\x0F\xCC")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::REXW, u2d("\x0F\xCC")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::NONE, u2d("\x0F\xCD")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::REXW, u2d("\x0F\xCD")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::NONE, u2d("\x0F\xCE")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::REXW, u2d("\x0F\xCE")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::NONE, u2d("\x0F\xCF")}, {{-1, Mnemonic::BSWAP}}},
        {{Prefix::REXW, u2d("\x0F\xCF")}, {{-1, Mnemonic::BSWAP}}},

        // SAL
        {{Prefix::NONE, u2d("\xD0")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},
        {{Prefix::REX, u2d("\xD0")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},

        {{Prefix::NONE, u2d("\xD2")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},
        {{Prefix::REX, u2d("\xD2")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},

        {{Prefix::NONE, u2d("\xC0")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},
        {{Prefix::REX, u2d("\xC0")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},

        {{Prefix::P66, u2d("\xD1")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},
        {{Prefix::NONE, u2d("\xD1")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},
        {{Prefix::REXW, u2d("\xD1")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},

        {{Prefix::P66, u2d("\xD3")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},
        {{Prefix::NONE, u2d("\xD3")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},
        {{Prefix::REXW, u2d("\xD3")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},

        {{Prefix::P66, u2d("\xC1")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},
        {{Prefix::NONE, u2d("\xC1")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},
        {{Prefix::REXW, u2d("\xC1")},
         {{4, Mnemonic::SAL},
          {7, Mnemonic::SAR},
          {5, Mnemonic::SHR},
          {2, Mnemonic::RCL},
          {3, Mnemonic::RCR},
          {0, Mnemonic::ROL},
          {1, Mnemonic::ROR}}},

        {{Prefix::P66, u2d("\x0F\xA4")}, {{-1, Mnemonic::SHLD}}},
        {{Prefix::NONE, u2d("\x0F\xA4")}, {{-1, Mnemonic::SHLD}}},
        {{Prefix::REXW, u2d("\x0F\xA4")}, {{-1, Mnemonic::SHLD}}},
        {{Prefix::P66, u2d("\x0F\xA5")}, {{-1, Mnemonic::SHLD}}},
        {{Prefix::NONE, u2d("\x0F\xA5")}, {{-1, Mnemonic::SHLD}}},
        {{Prefix::REXW, u2d("\x0F\xA5")}, {{-1, Mnemonic::SHLD}}},

        {{Prefix::P66, u2d("\x0F\xAC")}, {{-1, Mnemonic::SHRD}}},
        {{Prefix::NONE, u2d("\x0F\xAC")}, {{-1, Mnemonic::SHRD}}},
        {{Prefix::REXW, u2d("\x0F\xAC")}, {{-1, Mnemonic::SHRD}}},
        {{Prefix::P66, u2d("\x0F\xAD")}, {{-1, Mnemonic::SHRD}}},
        {{Prefix::NONE, u2d("\x0F\xAD")}, {{-1, Mnemonic::SHRD}}},
        {{Prefix::REXW, u2d("\x0F\xAD")}, {{-1, Mnemonic::SHRD}}},

        // POP
        {{Prefix::NONE, u2d("\x8F")}, {{0, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x58")}, {{-1, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x59")}, {{-1, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x5A")}, {{-1, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x5B")}, {{-1, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x5C")}, {{-1, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x5D")}, {{-1, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x5E")}, {{-1, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x5F")}, {{-1, Mnemonic::POP}}},

        // PUSH
        {{Prefix::NONE, u2d("\x50")}, {{-1, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x51")}, {{-1, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x52")}, {{-1, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x53")}, {{-1, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x54")}, {{-1, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x55")}, {{-1, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x56")}, {{-1, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x57")}, {{-1, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x6A")}, {{-1, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x68")}, {{-1, Mnemonic::PUSH}}},
};

// Lookup table for operand information
// (prefix, operator, opcode) -> (encoding, remaining opecodes, operands)
const std::unordered_map<
    std::tuple<Prefix, Mnemonic, int>,
    std::tuple<OpEnc, std::vector<std::string>, std::vector<Operand>>>
    OPERAND_LOOKUP = {
        // SETNE
        {{Prefix::NONE, Mnemonic::SETNE, u2d("\x0F\x95")},
         {OpEnc::M, {}, {Operand::rm8}}},
        {{Prefix::REX, Mnemonic::SETNE, u2d("\x0F\x95")},
         {OpEnc::M, {}, {Operand::rm8}}},

        {{Prefix::NONE, Mnemonic::FADD, u2d("\xD8")},
         {OpEnc::M, {"0"}, {Operand::m32fp}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xDC")},
         {OpEnc::M, {"0"}, {Operand::m64fp}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xD8\xC0")},
         {OpEnc::NP, {"0"}, {Operand::st0, Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xD8\xC1")},
         {OpEnc::NP, {"1"}, {Operand::st0, Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xD8\xC2")},
         {OpEnc::NP, {"2"}, {Operand::st0, Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xD8\xC3")},
         {OpEnc::NP, {"3"}, {Operand::st0, Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xD8\xC4")},
         {OpEnc::NP, {"4"}, {Operand::st0, Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xD8\xC5")},
         {OpEnc::NP, {"5"}, {Operand::st0, Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xD8\xC6")},
         {OpEnc::NP, {"6"}, {Operand::st0, Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xD8\xC7")},
         {OpEnc::NP, {"7"}, {Operand::st0, Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xDC\xC0")},
         {OpEnc::NP, {"0"}, {Operand::sti, Operand::st0}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xDC\xC1")},
         {OpEnc::NP, {"1"}, {Operand::sti, Operand::st0}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xDC\xC2")},
         {OpEnc::NP, {"2"}, {Operand::sti, Operand::st0}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xDC\xC3")},
         {OpEnc::NP, {"3"}, {Operand::sti, Operand::st0}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xDC\xC4")},
         {OpEnc::NP, {"4"}, {Operand::sti, Operand::st0}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xDC\xC5")},
         {OpEnc::NP, {"5"}, {Operand::sti, Operand::st0}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xDC\xC6")},
         {OpEnc::NP, {"6"}, {Operand::sti, Operand::st0}}},
        {{Prefix::NONE, Mnemonic::FADD, u2d("\xDC\xC7")},
         {OpEnc::NP, {"7"}, {Operand::sti, Operand::st0}}},

        // FXCH
        {{Prefix::NONE, Mnemonic::FXCH, u2d("\xD9\xC8")},
         {OpEnc::NP, {"0"}, {Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FXCH, u2d("\xD9\xC9")},
         {OpEnc::NP, {"1"}, {Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FXCH, u2d("\xD9\xCA")},
         {OpEnc::NP, {"2"}, {Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FXCH, u2d("\xD9\xCB")},
         {OpEnc::NP, {"3"}, {Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FXCH, u2d("\xD9\xCC")},
         {OpEnc::NP, {"4"}, {Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FXCH, u2d("\xD9\xCD")},
         {OpEnc::NP, {"5"}, {Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FXCH, u2d("\xD9\xCE")},
         {OpEnc::NP, {"6"}, {Operand::sti}}},
        {{Prefix::NONE, Mnemonic::FXCH, u2d("\xD9\xCF")},
         {OpEnc::NP, {"7"}, {Operand::sti}}},

        // CMOVE
        {{Prefix::NONE, Mnemonic::CMOVE, u2d("\x0F\x44")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},

        // MOVAPS
        {{Prefix::NONE, Mnemonic::MOVAPS, u2d("\x0F\x28")},
         {OpEnc::A, {"/r"}, {Operand::xmm, Operand::xm128}}},
        {{Prefix::NONE, Mnemonic::MOVAPS, u2d("\x0F\x29")},
         {OpEnc::B, {"/r"}, {Operand::xm128, Operand::xmm}}},

        // ENDBR
        {{Prefix::NONE, Mnemonic::ENDBR64, u2d("\xF3\x0F\x1E\xFA")},
         {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::ENDBR32, u2d("\xF3\x0F\x1E\xFB")},
         {OpEnc::NP, {}, {}}},

        // IN
        {{Prefix::NONE, Mnemonic::IN, u2d("\xE4")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::IN, u2d("\xE5")},
         {OpEnc::I, {"ib"}, {Operand::eax, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::IN, u2d("\xEC")},
         {OpEnc::NP, {}, {Operand::al, Operand::dx}}},
        {{Prefix::NONE, Mnemonic::IN, u2d("\xED")},
         {OpEnc::NP, {}, {Operand::eax, Operand::dx}}},

        // OUT
        {{Prefix::NONE, Mnemonic::OUT, u2d("\xE6")},
         {OpEnc::I, {"ib"}, {Operand::imm8, Operand::al}}},
        {{Prefix::NONE, Mnemonic::OUT, u2d("\xE7")},
         {OpEnc::I, {"ib"}, {Operand::imm8, Operand::eax}}},
        {{Prefix::NONE, Mnemonic::OUT, u2d("\xEE")},
         {OpEnc::NP, {}, {Operand::dx, Operand::al}}},
        {{Prefix::NONE, Mnemonic::OUT, u2d("\xEF")},
         {OpEnc::NP, {}, {Operand::dx, Operand::eax}}},

        // LOOP
        {{Prefix::NONE, Mnemonic::LOOP, u2d("\xE2")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::LOOPE, u2d("\xE1")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::LOOPNE, u2d("\xE0")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},

        // SHLD
        {{Prefix::NONE, Mnemonic::SHLD, u2d("\x0F\xA4")},
         {OpEnc::MRI, {"ib"}, {Operand::rm32, Operand::reg32, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SHLD, u2d("\x0F\xA5")},
         {OpEnc::MRC, {"/r"}, {Operand::rm32, Operand::reg32, Operand::cl}}},
        {{Prefix::REXW, Mnemonic::SHLD, u2d("\x0F\xA4")},
         {OpEnc::MRI, {"ib"}, {Operand::rm64, Operand::reg64, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::SHLD, u2d("\x0F\xA5")},
         {OpEnc::MRC, {"/r"}, {Operand::rm64, Operand::reg64, Operand::cl}}},

        // SHRD
        {{Prefix::NONE, Mnemonic::SHRD, u2d("\x0F\xAC")},
         {OpEnc::MRI, {"ib"}, {Operand::rm32, Operand::reg32, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SHRD, u2d("\x0F\xAD")},
         {OpEnc::MRC, {"/r"}, {Operand::rm32, Operand::reg32, Operand::cl}}},
        {{Prefix::REXW, Mnemonic::SHRD, u2d("\x0F\xAC")},
         {OpEnc::MRI, {"ib"}, {Operand::rm64, Operand::reg64, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::SHRD, u2d("\x0F\xAD")},
         {OpEnc::MRC, {"/r"}, {Operand::rm64, Operand::reg64, Operand::cl}}},

        {{Prefix::NONE, Mnemonic::JECXZ, u2d("\xE3")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::INSB, u2d("\x6C")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::INSW, u2d("\x6D")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::OUTSB, u2d("\x6E")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::OUTSW, u2d("\x6F")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::STOSB, u2d("\xAA")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::STOSW, u2d("\xAB")}, {OpEnc::NP, {}, {}}},
        {{Prefix::REXW, Mnemonic::STOSQ, u2d("\xAB")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::SCASB, u2d("\xAE")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::SCASW, u2d("\xAF")}, {OpEnc::NP, {}, {}}},
        {{Prefix::REXW, Mnemonic::SCASQ, u2d("\xAF")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::LODSB, u2d("\xAC")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::LODSW, u2d("\xAD")}, {OpEnc::NP, {}, {}}},
        {{Prefix::REXW, Mnemonic::LODSQ, u2d("\xAD")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::MOVSB, u2d("\xA4")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::MOVSW, u2d("\xA5")}, {OpEnc::NP, {}, {}}},
        {{Prefix::REXW, Mnemonic::MOVSQ, u2d("\xA5")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::CMPSB, u2d("\xA6")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::CMPSW, u2d("\xA7")}, {OpEnc::NP, {}, {}}},
        {{Prefix::REXW, Mnemonic::CMPSQ, u2d("\xA7")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::CPUID, u2d("\x0F\xA2")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::LEAVE, u2d("\xC9")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::CLC, u2d("\xF8")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::CLD, u2d("\xFC")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::STC, u2d("\xF9")}, {OpEnc::NP, {}, {}}},
        // ADD
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x04")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x05")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x05")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::ADD, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x00")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x01")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x01")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x02")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::ADD, u2d("\x02")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x03")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x03")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // ADC
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x14")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x15")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x15")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::ADC, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x10")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::REX, Mnemonic::ADC, u2d("\x10")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x11")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x11")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x12")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::ADC, u2d("\x12")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x13")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x13")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // SUB
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x2C")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x2D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x2D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::SUB, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x29")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x29")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x2A")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::SUB, u2d("\x2A")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x2B")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x2B")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x28")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::REX, Mnemonic::SUB, u2d("\x28")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},

        // SBB
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x1C")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x1D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x1D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::SBB, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x19")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x19")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x1A")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::SBB, u2d("\x1A")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x1B")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x1B")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // INC
        {{Prefix::NONE, Mnemonic::INC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm8}}},
        {{Prefix::REX, Mnemonic::INC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::INC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::INC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm64}}},

        // DEC
        {{Prefix::NONE, Mnemonic::DEC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm8}}},
        {{Prefix::REX, Mnemonic::DEC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::DEC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::DEC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm64}}},

        // NEG
        {{Prefix::NONE, Mnemonic::NEG, u2d("\xF6")},
         {OpEnc::M, {}, {Operand::rm8}}},
        {{Prefix::REX, Mnemonic::NEG, u2d("\xF6")},
         {OpEnc::M, {}, {Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::NEG, u2d("\xF7")},
         {OpEnc::M, {}, {Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::NEG, u2d("\xF7")},
         {OpEnc::M, {}, {Operand::rm64}}},

        // AND
        {{Prefix::NONE, Mnemonic::AND, u2d("\x24")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x25")},
         {OpEnc::I, {"iw"}, {Operand::ax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x25")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x25")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::AND, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm64, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x20")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::REX, Mnemonic::AND, u2d("\x20")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x22")},
         {OpEnc::RM, {"/r"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::AND, u2d("\x22")},
         {OpEnc::RM, {"/r"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x21")},
         {OpEnc::MR, {"/r"}, {Operand::rm16, Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x21")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x21")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x23")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x23")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x23")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // OR
        {{Prefix::NONE, Mnemonic::OR, u2d("\x0C")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x0D")},
         {OpEnc::I, {"iw"}, {Operand::ax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x0D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x0D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::OR, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm64, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x09")},
         {OpEnc::MR, {"/r"}, {Operand::rm16, Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x08")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::REX, Mnemonic::OR, u2d("\x08")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x09")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x09")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x0B")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x0B")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x0B")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // XOR
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x30")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::REX, Mnemonic::XOR, u2d("\x30")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x34")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x35")},
         {OpEnc::I, {"iw"}, {Operand::ax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x35")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x35")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x31")},
         {OpEnc::MR, {"/r"}, {Operand::rm16, Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x31")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x31")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x33")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x33")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x33")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // NOT
        {{Prefix::NONE, Mnemonic::NOT, u2d("\xF6")},
         {OpEnc::RM, {}, {Operand::reg8}}},
        {{Prefix::REX, Mnemonic::NOT, u2d("\xF6")},
         {OpEnc::RM, {}, {Operand::reg8}}},
        {{Prefix::P66, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg64}}},

        // MUL
        {{Prefix::NONE, Mnemonic::MUL, u2d("\xF6")},
         {OpEnc::RM, {}, {Operand::reg8}}},
        {{Prefix::REX, Mnemonic::MUL, u2d("\xF6")},
         {OpEnc::RM, {}, {Operand::reg8}}},
        {{Prefix::P66, Mnemonic::MUL, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::MUL, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::MUL, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg64}}},

        // IMUL
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\xF6")},
         {OpEnc::MR, {"/r"}, {Operand::rm8}}},
        {{Prefix::REX, Mnemonic::IMUL, u2d("\xF6")},
         {OpEnc::MR, {"/r"}, {Operand::rm8}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\xF7")},
         {OpEnc::MR, {"/r"}, {Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\xF7")},
         {OpEnc::MR, {"/r"}, {Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\xF7")},
         {OpEnc::MR, {"/r"}, {Operand::rm64}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\x0F\xAF")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x0F\xAF")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x0F\xAF")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg16, Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg32, Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg64, Operand::rm64, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg64, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"iw"}, {Operand::reg16, Operand::rm16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"id"}, {Operand::reg32, Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"id"}, {Operand::reg64, Operand::rm64, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"iw"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"id"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"id"}, {Operand::reg64, Operand::imm32}}},

        // DIV
        {{Prefix::NONE, Mnemonic::DIV, u2d("\xF6")},
         {OpEnc::M, {"/r"}, {Operand::rm8}}},
        {{Prefix::REX, Mnemonic::DIV, u2d("\xF6")},
         {OpEnc::M, {"/r"}, {Operand::rm8}}},
        {{Prefix::P66, Mnemonic::DIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::DIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::DIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm64}}},

        // IDIV
        {{Prefix::NONE, Mnemonic::IDIV, u2d("\xF6")},
         {OpEnc::M, {"/r"}, {Operand::rm8}}},
        {{Prefix::REX, Mnemonic::IDIV, u2d("\xF6")},
         {OpEnc::M, {"/r"}, {Operand::rm8}}},
        {{Prefix::P66, Mnemonic::IDIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::IDIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::IDIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm64}}},

        // CMP
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x3C")},
         {OpEnc::I, {"id"}, {Operand::al, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::CMP, u2d("\x3D")},
         {OpEnc::I, {"id"}, {Operand::ax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x3D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x3D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::CMP, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::CMP, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm64, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::CMP, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x38")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::REX, Mnemonic::CMP, u2d("\x38")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::P66, Mnemonic::CMP, u2d("\x39")},
         {OpEnc::MR, {"/r"}, {Operand::rm16, Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x39")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x39")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::P66, Mnemonic::CMP, u2d("\x3B")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x3A")},
         {OpEnc::RM, {"/r"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::CMP, u2d("\x3A")},
         {OpEnc::RM, {"/r"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x3B")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x3B")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // TEST
        {{Prefix::NONE, Mnemonic::TEST, u2d("\xA8")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::TEST, u2d("\xA9")},
         {OpEnc::I, {"iw"}, {Operand::ax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\xA9")},
         {OpEnc::I, {"id"}, {Operand::ax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::TEST, u2d("\xA9")},
         {OpEnc::I, {"id"}, {Operand::ax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\xF6")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::TEST, u2d("\xF6")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::TEST, u2d("\xF7")},
         {OpEnc::MI, {"iw"}, {Operand::rm16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\xF7")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::TEST, u2d("\xF7")},
         {OpEnc::MI, {"id"}, {Operand::rm64, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\x84")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::REX, Mnemonic::TEST, u2d("\x84")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::P66, Mnemonic::TEST, u2d("\x85")},
         {OpEnc::MR, {"/r"}, {Operand::rm16, Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\x85")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::TEST, u2d("\x85")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},

        // MOV
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x88")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\x88")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\x89")},
         {OpEnc::MR, {"/r"}, {Operand::rm16, Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x89")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\x89")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x8A")},
         {OpEnc::RM, {"/r"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\x8A")},
         {OpEnc::RM, {"/r"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\x8B")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x8B")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\x8B")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x8C")},
         {OpEnc::MR, {"/r"}, {Operand::rm16, Operand::sreg}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\x8C")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::sreg}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x8E")},
         {OpEnc::RM, {"/r"}, {Operand::sreg, Operand::rm16}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\x8E")},
         {OpEnc::RM, {"/r"}, {Operand::sreg, Operand::rm64}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xA0")},
         {OpEnc::FD, {}, {Operand::al, Operand::moffs8}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xA0")},
         {OpEnc::FD, {}, {Operand::al, Operand::moffs8}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xA1")},
         {OpEnc::FD, {}, {Operand::ax, Operand::moffs16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xA1")},
         {OpEnc::FD, {}, {Operand::eax, Operand::moffs32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xA1")},
         {OpEnc::FD, {}, {Operand::rax, Operand::moffs64}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xA2")},
         {OpEnc::TD, {}, {Operand::moffs8, Operand::al}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xA2")},
         {OpEnc::TD, {}, {Operand::moffs8, Operand::al}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xA3")},
         {OpEnc::TD, {}, {Operand::moffs16, Operand::ax}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xA3")},
         {OpEnc::TD, {}, {Operand::moffs64, Operand::rax}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB0")},
         {OpEnc::OI, {"0"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB0")},
         {OpEnc::OI, {"0"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB1")},
         {OpEnc::OI, {"1"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB1")},
         {OpEnc::OI, {"1"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB2")},
         {OpEnc::OI, {"2"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB2")},
         {OpEnc::OI, {"2"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB3")},
         {OpEnc::OI, {"3"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB3")},
         {OpEnc::OI, {"3"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB4")},
         {OpEnc::OI, {"4"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB4")},
         {OpEnc::OI, {"4"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB5")},
         {OpEnc::OI, {"5"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB5")},
         {OpEnc::OI, {"5"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB6")},
         {OpEnc::OI, {"6"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB6")},
         {OpEnc::OI, {"6"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB7")},
         {OpEnc::OI, {"7"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB7")},
         {OpEnc::OI, {"7"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xB8")},
         {OpEnc::OI, {"0"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB8")},
         {OpEnc::OI, {"0"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xB8")},
         {OpEnc::OI, {"0"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xB9")},
         {OpEnc::OI, {"1"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB9")},
         {OpEnc::OI, {"1"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xB9")},
         {OpEnc::OI, {"1"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBA")},
         {OpEnc::OI, {"2"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBA")},
         {OpEnc::OI, {"2"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBA")},
         {OpEnc::OI, {"2"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBB")},
         {OpEnc::OI, {"3"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBB")},
         {OpEnc::OI, {"3"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBB")},
         {OpEnc::OI, {"3"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBC")},
         {OpEnc::OI, {"4"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBC")},
         {OpEnc::OI, {"4"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBC")},
         {OpEnc::OI, {"4"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBD")},
         {OpEnc::OI, {"5"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBD")},
         {OpEnc::OI, {"5"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBD")},
         {OpEnc::OI, {"5"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBE")},
         {OpEnc::OI, {"6"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBE")},
         {OpEnc::OI, {"6"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBE")},
         {OpEnc::OI, {"6"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBF")},
         {OpEnc::OI, {"7"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBF")},
         {OpEnc::OI, {"7"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBF")},
         {OpEnc::OI, {"7"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xC6")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xC6")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xC7")},
         {OpEnc::MI, {"iw"}, {Operand::rm16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xC7")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xC7")},
         {OpEnc::MI, {"id"}, {Operand::rm64, Operand::imm32}}},

        // CBW
        {{Prefix::P66, Mnemonic::CBW, u2d("\x98")}, {OpEnc::NP, {}, {}}},

        // CWDE
        {{Prefix::NONE, Mnemonic::CWDE, u2d("\x98")}, {OpEnc::NP, {}, {}}},

        // CDQE
        {{Prefix::REXW, Mnemonic::CDQE, u2d("\x98")}, {OpEnc::NP, {}, {}}},

        // CWD
        {{Prefix::P66, Mnemonic::CWD, u2d("\x99")}, {OpEnc::NP, {}, {}}},

        // CDQ
        {{Prefix::NONE, Mnemonic::CDQ, u2d("\x99")}, {OpEnc::NP, {}, {}}},

        // CQO
        {{Prefix::REXW, Mnemonic::CQO, u2d("\x99")}, {OpEnc::NP, {}, {}}},

        // MOVSX
        {{Prefix::P66, Mnemonic::MOVSX, u2d("\x0F\xBE")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::MOVSX, u2d("\x0F\xBE")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::MOVSX, u2d("\x0F\xBE")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::MOVSX, u2d("\x0F\xBF")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm16}}},
        {{Prefix::REXW, Mnemonic::MOVSX, u2d("\x0F\xBF")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm16}}},
        {{Prefix::P66, Mnemonic::MOVZX, u2d("\x0F\xB6")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::MOVZX, u2d("\x0F\xB6")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::MOVZX, u2d("\x0F\xB6")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::MOVZX, u2d("\x0F\xB7")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm16}}},
        {{Prefix::REXW, Mnemonic::MOVZX, u2d("\x0F\xB7")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm32}}},

        // MOVSXD
        {{Prefix::REXW, Mnemonic::MOVSXD, u2d("\x63")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm32}}},

        // LEA
        {{Prefix::P66, Mnemonic::LEA, u2d("\x8D")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::m}}},
        {{Prefix::NONE, Mnemonic::LEA, u2d("\x8D")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::m}}},
        {{Prefix::REXW, Mnemonic::LEA, u2d("\x8D")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::m}}},

        // BSWAP
        {{Prefix::NONE, Mnemonic::BSWAP, u2d("\x0F\xC8")},
         {OpEnc::O, {"0"}, {Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::BSWAP, u2d("\x0F\xC8")},
         {OpEnc::O, {"0"}, {Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::BSWAP, u2d("\x0F\xC9")},
         {OpEnc::O, {"1"}, {Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::BSWAP, u2d("\x0F\xC9")},
         {OpEnc::O, {"1"}, {Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::BSWAP, u2d("\x0F\xCA")},
         {OpEnc::O, {"2"}, {Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::BSWAP, u2d("\x0F\xCA")},
         {OpEnc::O, {"2"}, {Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::BSWAP, u2d("\x0F\xCB")},
         {OpEnc::O, {"3"}, {Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::BSWAP, u2d("\x0F\xCB")},
         {OpEnc::O, {"3"}, {Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::BSWAP, u2d("\x0F\xCC")},
         {OpEnc::O, {"4"}, {Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::BSWAP, u2d("\x0F\xCC")},
         {OpEnc::O, {"4"}, {Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::BSWAP, u2d("\x0F\xCD")},
         {OpEnc::O, {"5"}, {Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::BSWAP, u2d("\x0F\xCD")},
         {OpEnc::O, {"5"}, {Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::BSWAP, u2d("\x0F\xCE")},
         {OpEnc::O, {"6"}, {Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::BSWAP, u2d("\x0F\xCE")},
         {OpEnc::O, {"6"}, {Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::BSWAP, u2d("\x0F\xCF")},
         {OpEnc::O, {"7"}, {Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::BSWAP, u2d("\x0F\xCF")},
         {OpEnc::O, {"7"}, {Operand::reg64}}},

        /*
        // XCHG AX, r16
        {{Prefix::P66, Mnemonic::XCHG, u2d("\x90"), Opcode_plus_rw()},
         {OpEnc::NP, {"rw"}, {Operand::ax, Operand::reg16}}},
        {{Prefix::P66, Mnemonic::XCHG, u2d("\x90"), Opcode_plus_rw()},
         {OpEnc::NP, {"rw"}, {Operand::reg16, Operand::ax}}},
        {{Prefix::NONE, Mnemonic::XCHG, u2d("\x90"), Opcode_plus_rd()},
         {OpEnc::NP, {"rd"}, {Operand::eax, Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::XCHG, u2d("\x90"), Opcode_plus_rd()},
         {OpEnc::NP, {"rd"}, {Operand::reg32, Operand::eax}}},
        {{Prefix::REXW, Mnemonic::XCHG, u2d("\x90"), Opcode_plus_rd()},
         {OpEnc::NP, {"rd"}, {Operand::rax, Operand::reg64}}},
        {{Prefix::REXW, Mnemonic::XCHG, u2d("\x90"), Opcode_plus_rd()},
         {OpEnc::NP, {"rd"}, {Operand::reg64, Operand::rax}}},
        */

        {{Prefix::NONE, Mnemonic::XCHG, u2d("\x86")},
         {OpEnc::RM, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::NONE, Mnemonic::XCHG, u2d("\x86")},
         {OpEnc::RM, {"/r"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::P66, Mnemonic::XCHG, u2d("\x87")},
         {OpEnc::RM, {"/r"}, {Operand::rm16, Operand::reg16}}},
        {{Prefix::P66, Mnemonic::XCHG, u2d("\x87")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::XCHG, u2d("\x87")},
         {OpEnc::RM, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::XCHG, u2d("\x87")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::XCHG, u2d("\x87")},
         {OpEnc::RM, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::REXW, Mnemonic::XCHG, u2d("\x87")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // NOP
        {{Prefix::NONE, Mnemonic::NOP, u2d("\x90")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::NOP, u2d("\x0F\x1F")},
         {OpEnc::M, {"0"}, {Operand::rm32}}},

        // RET
        {{Prefix::NONE, Mnemonic::RET, u2d("\xC3")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::RET, u2d("\xCB")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::RET, u2d("\xC2")},
         {OpEnc::I, {"iw"}, {Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::RET, u2d("\xCA")},
         {OpEnc::I, {"iw"}, {Operand::imm16}}},

        // CALL
        {{Prefix::NONE, Mnemonic::CALL, u2d("\xE8")},
         {OpEnc::D, {}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::CALL, u2d("\xFF")},
         {OpEnc::D, {"2"}, {Operand::rm64}}},

        // JCC
        {{Prefix::NONE, Mnemonic::JO, u2d("\x0F\x80")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JNO, u2d("\x0F\x81")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JNAE, u2d("\x0F\x82")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JNB, u2d("\x0F\x83")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JZ, u2d("\x0F\x84")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JNZ, u2d("\x0F\x85")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JNA, u2d("\x0F\x86")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JNBE, u2d("\x0F\x87")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JS, u2d("\x0F\x88")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JNS, u2d("\x0F\x89")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JP, u2d("\x0F\x8A")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JPO, u2d("\x0F\x8B")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JNGE, u2d("\x0F\x8C")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JNL, u2d("\x0F\x8D")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JNG, u2d("\x0F\x8E")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JNLE, u2d("\x0F\x8F")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},

        {{Prefix::NONE, Mnemonic::JO, u2d("\x70")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JNO, u2d("\x71")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JNAE, u2d("\x72")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JNB, u2d("\x73")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JZ, u2d("\x74")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JNZ, u2d("\x75")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JNA, u2d("\x76")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JNBE, u2d("\x77")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JS, u2d("\x78")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JNS, u2d("\x79")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JP, u2d("\x7A")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JPO, u2d("\x7B")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JNGE, u2d("\x7C")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JNL, u2d("\x7D")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JNG, u2d("\x7E")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JNLE, u2d("\x7F")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},

        // JMP
        {{Prefix::NONE, Mnemonic::JMP, u2d("\xEB")},
         {OpEnc::D, {"cb"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JMP, u2d("\xE9")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JMP, u2d("\xFF")},
         {OpEnc::M, {"4"}, {Operand::rm64}}},

        // POP
        {{Prefix::NONE, Mnemonic::POP, u2d("\x8F")},
         {OpEnc::M, {"0"}, {Operand::rm64}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x58")},
         {OpEnc::O, {"0"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x59")},
         {OpEnc::O, {"1"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x5A")},
         {OpEnc::O, {"2"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x5B")},
         {OpEnc::O, {"3"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x5C")},
         {OpEnc::O, {"4"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x5D")},
         {OpEnc::O, {"5"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x5E")},
         {OpEnc::O, {"6"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x5F")},
         {OpEnc::O, {"7"}, {Operand::reg32}}},

        // PUSH
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\xFF")},
         {OpEnc::M, {"6"}, {Operand::rm32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x50")},
         {OpEnc::O, {"0"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x51")},
         {OpEnc::O, {"1"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x52")},
         {OpEnc::O, {"2"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x53")},
         {OpEnc::O, {"3"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x54")},
         {OpEnc::O, {"4"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x55")},
         {OpEnc::O, {"5"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x56")},
         {OpEnc::O, {"6"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x57")},
         {OpEnc::O, {"7"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x6A")},
         {OpEnc::I, {"ib"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x68")},
         {OpEnc::I, {"id"}, {Operand::imm32}}},

        {{Prefix::NONE, Mnemonic::SAL, u2d("\xD0")},
         {OpEnc::M1, {"4"}, {Operand::rm8, Operand::one}}},
        {{Prefix::REX, Mnemonic::SAL, u2d("\xD0")},
         {OpEnc::M1, {"4"}, {Operand::rm8, Operand::one}}},
        {{Prefix::NONE, Mnemonic::SAL, u2d("\xD2")},
         {OpEnc::MC, {"4"}, {Operand::rm8, Operand::cl}}},
        {{Prefix::REX, Mnemonic::SAL, u2d("\xD2")},
         {OpEnc::MC, {"4"}, {Operand::rm8, Operand::cl}}},
        {{Prefix::P66, Mnemonic::SAL, u2d("\xC0")},
         {OpEnc::MI, {"4"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SAL, u2d("\xC0")},
         {OpEnc::MI, {"4"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::SAL, u2d("\xD1")},
         {OpEnc::M1, {"4"}, {Operand::rm16, Operand::one}}},
        {{Prefix::NONE, Mnemonic::SAL, u2d("\xD1")},
         {OpEnc::M1, {"4"}, {Operand::rm32, Operand::one}}},
        {{Prefix::REXW, Mnemonic::SAL, u2d("\xD1")},
         {OpEnc::M1, {"4"}, {Operand::rm64, Operand::one}}},
        {{Prefix::P66, Mnemonic::SAL, u2d("\xD3")},
         {OpEnc::MC, {"4"}, {Operand::rm16, Operand::cl}}},
        {{Prefix::NONE, Mnemonic::SAL, u2d("\xD3")},
         {OpEnc::MC, {"4"}, {Operand::rm32, Operand::cl}}},
        {{Prefix::REXW, Mnemonic::SAL, u2d("\xD3")},
         {OpEnc::MC, {"4"}, {Operand::rm64, Operand::cl}}},
        {{Prefix::P66, Mnemonic::SAL, u2d("\xC1")},
         {OpEnc::MI, {"4"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SAL, u2d("\xC1")},
         {OpEnc::MI, {"4"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::SAL, u2d("\xC1")},
         {OpEnc::MI, {"4"}, {Operand::rm64, Operand::imm8}}},

        {{Prefix::NONE, Mnemonic::SAR, u2d("\xD0")},
         {OpEnc::M1, {"7"}, {Operand::rm8, Operand::one}}},
        {{Prefix::REX, Mnemonic::SAR, u2d("\xD0")},
         {OpEnc::M1, {"7"}, {Operand::rm8, Operand::one}}},
        {{Prefix::NONE, Mnemonic::SAR, u2d("\xD2")},
         {OpEnc::MC, {"7"}, {Operand::rm8, Operand::cl}}},
        {{Prefix::REX, Mnemonic::SAR, u2d("\xD2")},
         {OpEnc::MC, {"7"}, {Operand::rm8, Operand::cl}}},
        {{Prefix::P66, Mnemonic::SAR, u2d("\xC0")},
         {OpEnc::MI, {"7"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SAR, u2d("\xC0")},
         {OpEnc::MI, {"7"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::SAR, u2d("\xD1")},
         {OpEnc::M1, {"7"}, {Operand::rm16, Operand::one}}},
        {{Prefix::NONE, Mnemonic::SAR, u2d("\xD1")},
         {OpEnc::M1, {"7"}, {Operand::rm32, Operand::one}}},
        {{Prefix::REXW, Mnemonic::SAR, u2d("\xD1")},
         {OpEnc::M1, {"7"}, {Operand::rm64, Operand::one}}},
        {{Prefix::P66, Mnemonic::SAR, u2d("\xD3")},
         {OpEnc::MC, {"7"}, {Operand::rm16, Operand::cl}}},
        {{Prefix::NONE, Mnemonic::SAR, u2d("\xD3")},
         {OpEnc::MC, {"7"}, {Operand::rm32, Operand::cl}}},
        {{Prefix::REXW, Mnemonic::SAR, u2d("\xD3")},
         {OpEnc::MC, {"7"}, {Operand::rm64, Operand::cl}}},
        {{Prefix::P66, Mnemonic::SAR, u2d("\xC1")},
         {OpEnc::MI, {"7"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SAR, u2d("\xC1")},
         {OpEnc::MI, {"7"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::SAR, u2d("\xC1")},
         {OpEnc::MI, {"7"}, {Operand::rm64, Operand::imm8}}},

        {{Prefix::NONE, Mnemonic::SHR, u2d("\xD0")},
         {OpEnc::M1, {"5"}, {Operand::rm8, Operand::one}}},
        {{Prefix::REX, Mnemonic::SHR, u2d("\xD0")},
         {OpEnc::M1, {"5"}, {Operand::rm8, Operand::one}}},
        {{Prefix::NONE, Mnemonic::SHR, u2d("\xD2")},
         {OpEnc::MC, {"5"}, {Operand::rm8, Operand::cl}}},
        {{Prefix::REX, Mnemonic::SHR, u2d("\xD2")},
         {OpEnc::MC, {"5"}, {Operand::rm8, Operand::cl}}},
        {{Prefix::P66, Mnemonic::SHR, u2d("\xC0")},
         {OpEnc::MI, {"5"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SHR, u2d("\xC0")},
         {OpEnc::MI, {"5"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::SHR, u2d("\xD1")},
         {OpEnc::M1, {"5"}, {Operand::rm16, Operand::one}}},
        {{Prefix::NONE, Mnemonic::SHR, u2d("\xD1")},
         {OpEnc::M1, {"5"}, {Operand::rm32, Operand::one}}},
        {{Prefix::REXW, Mnemonic::SHR, u2d("\xD1")},
         {OpEnc::M1, {"5"}, {Operand::rm64, Operand::one}}},
        {{Prefix::P66, Mnemonic::SHR, u2d("\xD3")},
         {OpEnc::MC, {"5"}, {Operand::rm16, Operand::cl}}},
        {{Prefix::NONE, Mnemonic::SHR, u2d("\xD3")},
         {OpEnc::MC, {"5"}, {Operand::rm32, Operand::cl}}},
        {{Prefix::REXW, Mnemonic::SHR, u2d("\xD3")},
         {OpEnc::MC, {"5"}, {Operand::rm64, Operand::cl}}},
        {{Prefix::P66, Mnemonic::SHR, u2d("\xC1")},
         {OpEnc::MI, {"5"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SHR, u2d("\xC1")},
         {OpEnc::MI, {"5"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::SHR, u2d("\xC1")},
         {OpEnc::MI, {"5"}, {Operand::rm64, Operand::imm8}}},

        {{Prefix::NONE, Mnemonic::RCL, u2d("\xD0")},
         {OpEnc::M1, {"2"}, {Operand::rm8, Operand::one}}},
        {{Prefix::REX, Mnemonic::RCL, u2d("\xD0")},
         {OpEnc::M1, {"2"}, {Operand::rm8, Operand::one}}},
        {{Prefix::NONE, Mnemonic::RCL, u2d("\xD2")},
         {OpEnc::MC, {"2"}, {Operand::rm8, Operand::cl}}},
        {{Prefix::REX, Mnemonic::RCL, u2d("\xD2")},
         {OpEnc::MC, {"2"}, {Operand::rm8, Operand::cl}}},
        {{Prefix::P66, Mnemonic::RCL, u2d("\xC0")},
         {OpEnc::MI, {"2"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::RCL, u2d("\xC0")},
         {OpEnc::MI, {"2"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::RCL, u2d("\xD1")},
         {OpEnc::M1, {"2"}, {Operand::rm16, Operand::one}}},
        {{Prefix::NONE, Mnemonic::RCL, u2d("\xD1")},
         {OpEnc::M1, {"2"}, {Operand::rm32, Operand::one}}},
        {{Prefix::REXW, Mnemonic::RCL, u2d("\xD1")},
         {OpEnc::M1, {"2"}, {Operand::rm64, Operand::one}}},
        {{Prefix::P66, Mnemonic::RCL, u2d("\xD3")},
         {OpEnc::MC, {"2"}, {Operand::rm16, Operand::cl}}},
        {{Prefix::NONE, Mnemonic::RCL, u2d("\xD3")},
         {OpEnc::MC, {"2"}, {Operand::rm32, Operand::cl}}},
        {{Prefix::REXW, Mnemonic::RCL, u2d("\xD3")},
         {OpEnc::MC, {"2"}, {Operand::rm64, Operand::cl}}},
        {{Prefix::P66, Mnemonic::RCL, u2d("\xC1")},
         {OpEnc::MI, {"2"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::RCL, u2d("\xC1")},
         {OpEnc::MI, {"2"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::RCL, u2d("\xC1")},
         {OpEnc::MI, {"2"}, {Operand::rm64, Operand::imm8}}},

        {{Prefix::NONE, Mnemonic::RCR, u2d("\xD0")},
         {OpEnc::M1, {"3"}, {Operand::rm8, Operand::one}}},
        {{Prefix::REX, Mnemonic::RCR, u2d("\xD0")},
         {OpEnc::M1, {"3"}, {Operand::rm8, Operand::one}}},
        {{Prefix::NONE, Mnemonic::RCR, u2d("\xD2")},
         {OpEnc::MC, {"3"}, {Operand::rm8, Operand::cl}}},
        {{Prefix::REX, Mnemonic::RCR, u2d("\xD2")},
         {OpEnc::MC, {"3"}, {Operand::rm8, Operand::cl}}},
        {{Prefix::P66, Mnemonic::RCR, u2d("\xC0")},
         {OpEnc::MI, {"3"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::RCR, u2d("\xC0")},
         {OpEnc::MI, {"3"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::RCR, u2d("\xD1")},
         {OpEnc::M1, {"3"}, {Operand::rm16, Operand::one}}},
        {{Prefix::NONE, Mnemonic::RCR, u2d("\xD1")},
         {OpEnc::M1, {"3"}, {Operand::rm32, Operand::one}}},
        {{Prefix::REXW, Mnemonic::RCR, u2d("\xD1")},
         {OpEnc::M1, {"3"}, {Operand::rm64, Operand::one}}},
        {{Prefix::P66, Mnemonic::RCR, u2d("\xD3")},
         {OpEnc::MC, {"3"}, {Operand::rm16, Operand::cl}}},
        {{Prefix::NONE, Mnemonic::RCR, u2d("\xD3")},
         {OpEnc::MC, {"3"}, {Operand::rm32, Operand::cl}}},
        {{Prefix::REXW, Mnemonic::RCR, u2d("\xD3")},
         {OpEnc::MC, {"3"}, {Operand::rm64, Operand::cl}}},
        {{Prefix::P66, Mnemonic::RCR, u2d("\xC1")},
         {OpEnc::MI, {"3"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::RCR, u2d("\xC1")},
         {OpEnc::MI, {"3"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::RCR, u2d("\xC1")},
         {OpEnc::MI, {"3"}, {Operand::rm64, Operand::imm8}}},

        {{Prefix::NONE, Mnemonic::ROL, u2d("\xD0")},
         {OpEnc::M1, {"0"}, {Operand::rm8, Operand::one}}},
        {{Prefix::REX, Mnemonic::ROL, u2d("\xD0")},
         {OpEnc::M1, {"0"}, {Operand::rm8, Operand::one}}},
        {{Prefix::NONE, Mnemonic::ROL, u2d("\xD2")},
         {OpEnc::MC, {"0"}, {Operand::rm8, Operand::cl}}},
        {{Prefix::REX, Mnemonic::ROL, u2d("\xD2")},
         {OpEnc::MC, {"0"}, {Operand::rm8, Operand::cl}}},
        {{Prefix::P66, Mnemonic::ROL, u2d("\xC0")},
         {OpEnc::MI, {"0"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ROL, u2d("\xC0")},
         {OpEnc::MI, {"0"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::ROL, u2d("\xD1")},
         {OpEnc::M1, {"0"}, {Operand::rm16, Operand::one}}},
        {{Prefix::NONE, Mnemonic::ROL, u2d("\xD1")},
         {OpEnc::M1, {"0"}, {Operand::rm32, Operand::one}}},
        {{Prefix::REXW, Mnemonic::ROL, u2d("\xD1")},
         {OpEnc::M1, {"0"}, {Operand::rm64, Operand::one}}},
        {{Prefix::P66, Mnemonic::ROL, u2d("\xD3")},
         {OpEnc::MC, {"0"}, {Operand::rm16, Operand::cl}}},
        {{Prefix::NONE, Mnemonic::ROL, u2d("\xD3")},
         {OpEnc::MC, {"0"}, {Operand::rm32, Operand::cl}}},
        {{Prefix::REXW, Mnemonic::ROL, u2d("\xD3")},
         {OpEnc::MC, {"0"}, {Operand::rm64, Operand::cl}}},
        {{Prefix::P66, Mnemonic::ROL, u2d("\xC1")},
         {OpEnc::MI, {"0"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ROL, u2d("\xC1")},
         {OpEnc::MI, {"0"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::ROL, u2d("\xC1")},
         {OpEnc::MI, {"0"}, {Operand::rm64, Operand::imm8}}},

        {{Prefix::NONE, Mnemonic::ROR, u2d("\xD0")},
         {OpEnc::M1, {"1"}, {Operand::rm8, Operand::one}}},
        {{Prefix::REX, Mnemonic::ROR, u2d("\xD0")},
         {OpEnc::M1, {"1"}, {Operand::rm8, Operand::one}}},
        {{Prefix::NONE, Mnemonic::ROR, u2d("\xD2")},
         {OpEnc::MC, {"1"}, {Operand::rm8, Operand::cl}}},
        {{Prefix::REX, Mnemonic::ROR, u2d("\xD2")},
         {OpEnc::MC, {"1"}, {Operand::rm8, Operand::cl}}},
        {{Prefix::P66, Mnemonic::ROR, u2d("\xC0")},
         {OpEnc::MI, {"1"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ROR, u2d("\xC0")},
         {OpEnc::MI, {"1"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::ROR, u2d("\xD1")},
         {OpEnc::M1, {"1"}, {Operand::rm16, Operand::one}}},
        {{Prefix::NONE, Mnemonic::ROR, u2d("\xD1")},
         {OpEnc::M1, {"1"}, {Operand::rm32, Operand::one}}},
        {{Prefix::REXW, Mnemonic::ROR, u2d("\xD1")},
         {OpEnc::M1, {"1"}, {Operand::rm64, Operand::one}}},
        {{Prefix::P66, Mnemonic::ROR, u2d("\xD3")},
         {OpEnc::MC, {"1"}, {Operand::rm16, Operand::cl}}},
        {{Prefix::NONE, Mnemonic::ROR, u2d("\xD3")},
         {OpEnc::MC, {"1"}, {Operand::rm32, Operand::cl}}},
        {{Prefix::REXW, Mnemonic::ROR, u2d("\xD3")},
         {OpEnc::MC, {"1"}, {Operand::rm64, Operand::cl}}},
        {{Prefix::P66, Mnemonic::ROR, u2d("\xC1")},
         {OpEnc::MI, {"1"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ROR, u2d("\xC1")},
         {OpEnc::MI, {"1"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::ROR, u2d("\xC1")},
         {OpEnc::MI, {"1"}, {Operand::rm64, Operand::imm8}}},
};

const std::vector<std::pair<int, int>> MULTI_BYTES_OPECODES = {
    std::make_pair(4, u2d("\xF3\x0F\x1E\xFA")),
    std::make_pair(4, u2d("\xF3\x0F\x1E\xFB"))};
