#pragma once
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>

#include "constants.h"
#include "utils.h"

// Global lookup table for instructions
// (prefix, opcode) -> (reg -> operator)
const std::unordered_map<std::pair<Prefix, int>,
                         std::unordered_map<int, Mnemonic>>
    OP_LOOKUP = {
        // ADD, ADC, SUB, SBB, AND, OR, XOR, CMP
        {{Prefix::NONE, u2d("\x04")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::NONE, u2d("\x14")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::NONE, u2d("\x2C")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::NONE, u2d("\x1C")}, {{-1, Mnemonic::SBB}}},

        {{Prefix::NONE, u2d("\x24")}, {{-1, Mnemonic::AND}}},
        {{Prefix::NONE, u2d("\x0C")}, {{-1, Mnemonic::OR}}},
        {{Prefix::NONE, u2d("\x34")}, {{-1, Mnemonic::XOR}}},

        {{Prefix::NONE, u2d("\x3C")}, {{-1, Mnemonic::CMP}}},

        {{Prefix::NONE, u2d("\x05")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::REXW, u2d("\x05")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::NONE, u2d("\x15")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::REXW, u2d("\x15")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::NONE, u2d("\x2D")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::REXW, u2d("\x2D")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::NONE, u2d("\x1D")}, {{-1, Mnemonic::SBB}}},
        {{Prefix::REXW, u2d("\x1D")}, {{-1, Mnemonic::SBB}}},

        {{Prefix::NONE, u2d("\x25")}, {{-1, Mnemonic::AND}}},
        {{Prefix::REXW, u2d("\x25")}, {{-1, Mnemonic::AND}}},
        {{Prefix::P66, u2d("\x25")}, {{-1, Mnemonic::AND}}},
        {{Prefix::NONE, u2d("\x0D")}, {{-1, Mnemonic::OR}}},
        {{Prefix::REXW, u2d("\x0D")}, {{-1, Mnemonic::OR}}},
        {{Prefix::P66, u2d("\x0D")}, {{-1, Mnemonic::OR}}},
        {{Prefix::NONE, u2d("\x35")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::REXW, u2d("\x35")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::P66, u2d("\x35")}, {{-1, Mnemonic::XOR}}},

        {{Prefix::NONE, u2d("\x80")},
         {{0, Mnemonic::ADD},
          {2, Mnemonic::ADC},
          {5, Mnemonic::SUB},
          {3, Mnemonic::SBB},
          {4, Mnemonic::AND},
          {1, Mnemonic::OR},
          {6, Mnemonic::XOR},
          {7, Mnemonic::CMP}}},
        {{Prefix::REX, u2d("\x80")},
         {{0, Mnemonic::ADD},
          {2, Mnemonic::ADC},
          {5, Mnemonic::SUB},
          {3, Mnemonic::SBB},
          {4, Mnemonic::AND},
          {1, Mnemonic::OR},
          {6, Mnemonic::XOR},
          {7, Mnemonic::CMP}}},

        {{Prefix::NONE, u2d("\x81")},
         {{0, Mnemonic::ADD},
          {2, Mnemonic::ADC},
          {5, Mnemonic::SUB},
          {3, Mnemonic::SBB},
          {4, Mnemonic::AND},
          {1, Mnemonic::OR},
          {6, Mnemonic::XOR},
          {7, Mnemonic::CMP}}},
        {{Prefix::REXW, u2d("\x81")},
         {{0, Mnemonic::ADD},
          {2, Mnemonic::ADC},
          {5, Mnemonic::SUB},
          {3, Mnemonic::SBB},
          {4, Mnemonic::AND},
          {1, Mnemonic::OR},
          {6, Mnemonic::XOR},
          {7, Mnemonic::CMP}}},

        {{Prefix::NONE, u2d("\x83")},
         {{0, Mnemonic::ADD},
          {2, Mnemonic::ADC},
          {5, Mnemonic::SUB},
          {3, Mnemonic::SBB},
          {4, Mnemonic::AND},
          {1, Mnemonic::OR},
          {6, Mnemonic::XOR},
          {7, Mnemonic::CMP}}},
        {{Prefix::REXW, u2d("\x83")},
         {{0, Mnemonic::ADD},
          {2, Mnemonic::ADC},
          {5, Mnemonic::SUB},
          {3, Mnemonic::SBB},
          {4, Mnemonic::AND},
          {1, Mnemonic::OR},
          {6, Mnemonic::XOR},
          {7, Mnemonic::CMP}}},

        {{Prefix::NONE, u2d("\x00")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::REX, u2d("\x00")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::NONE, u2d("\x10")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::REX, u2d("\x10")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::NONE, u2d("\x28")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::REX, u2d("\x28")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::NONE, u2d("\x18")}, {{-1, Mnemonic::SBB}}},
        {{Prefix::REX, u2d("\x18")}, {{-1, Mnemonic::SBB}}},
        {{Prefix::NONE, u2d("\x20")}, {{-1, Mnemonic::AND}}},
        {{Prefix::REX, u2d("\x20")}, {{-1, Mnemonic::AND}}},
        {{Prefix::NONE, u2d("\x08")}, {{-1, Mnemonic::OR}}},
        {{Prefix::REX, u2d("\x08")}, {{-1, Mnemonic::OR}}},
        {{Prefix::NONE, u2d("\x30")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::REX, u2d("\x30")}, {{-1, Mnemonic::XOR}}},

        {{Prefix::NONE, u2d("\x01")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::REXW, u2d("\x01")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::NONE, u2d("\x11")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::REXW, u2d("\x11")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::NONE, u2d("\x29")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::REXW, u2d("\x29")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::NONE, u2d("\x19")}, {{-1, Mnemonic::SBB}}},
        {{Prefix::REXW, u2d("\x19")}, {{-1, Mnemonic::SBB}}},

        {{Prefix::NONE, u2d("\x20")}, {{-1, Mnemonic::AND}}},
        {{Prefix::REXW, u2d("\x20")}, {{-1, Mnemonic::AND}}},
        {{Prefix::P66, u2d("\x20")}, {{-1, Mnemonic::AND}}},
        {{Prefix::NONE, u2d("\x08")}, {{-1, Mnemonic::OR}}},
        {{Prefix::REXW, u2d("\x08")}, {{-1, Mnemonic::OR}}},
        {{Prefix::P66, u2d("\x08")}, {{-1, Mnemonic::OR}}},
        {{Prefix::NONE, u2d("\x30")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::REXW, u2d("\x30")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::P66, u2d("\x30")}, {{-1, Mnemonic::XOR}}},

        {{Prefix::NONE, u2d("\x02")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::REX, u2d("\x02")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::NONE, u2d("\x12")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::REX, u2d("\x12")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::NONE, u2d("\x2A")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::REX, u2d("\x2A")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::NONE, u2d("\x1A")}, {{-1, Mnemonic::SBB}}},
        {{Prefix::REX, u2d("\x1A")}, {{-1, Mnemonic::SBB}}},

        {{Prefix::NONE, u2d("\x21")}, {{-1, Mnemonic::AND}}},
        {{Prefix::REXW, u2d("\x21")}, {{-1, Mnemonic::AND}}},
        {{Prefix::P66, u2d("\x21")}, {{-1, Mnemonic::AND}}},
        {{Prefix::NONE, u2d("\x09")}, {{-1, Mnemonic::OR}}},
        {{Prefix::REXW, u2d("\x09")}, {{-1, Mnemonic::OR}}},
        {{Prefix::P66, u2d("\x09")}, {{-1, Mnemonic::OR}}},
        {{Prefix::NONE, u2d("\x31")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::REXW, u2d("\x31")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::P66, u2d("\x31")}, {{-1, Mnemonic::XOR}}},

        {{Prefix::NONE, u2d("\x03")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::REXW, u2d("\x03")}, {{-1, Mnemonic::ADD}}},
        {{Prefix::NONE, u2d("\x13")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::REXW, u2d("\x13")}, {{-1, Mnemonic::ADC}}},
        {{Prefix::NONE, u2d("\x2B")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::REXW, u2d("\x2B")}, {{-1, Mnemonic::SUB}}},
        {{Prefix::NONE, u2d("\x1B")}, {{-1, Mnemonic::SBB}}},
        {{Prefix::REXW, u2d("\x1B")}, {{-1, Mnemonic::SBB}}},

        {{Prefix::NONE, u2d("\x22")}, {{-1, Mnemonic::AND}}},
        {{Prefix::REX, u2d("\x22")}, {{-1, Mnemonic::AND}}},
        {{Prefix::NONE, u2d("\x0A")}, {{-1, Mnemonic::OR}}},
        {{Prefix::REX, u2d("\x0A")}, {{-1, Mnemonic::OR}}},
        {{Prefix::NONE, u2d("\x32")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::REX, u2d("\x32")}, {{-1, Mnemonic::XOR}}},

        {{Prefix::NONE, u2d("\x23")}, {{-1, Mnemonic::AND}}},
        {{Prefix::REXW, u2d("\x23")}, {{-1, Mnemonic::AND}}},
        {{Prefix::P66, u2d("\x23")}, {{-1, Mnemonic::AND}}},
        {{Prefix::NONE, u2d("\x0B")}, {{-1, Mnemonic::OR}}},
        {{Prefix::REXW, u2d("\x0B")}, {{-1, Mnemonic::OR}}},
        {{Prefix::P66, u2d("\x0B")}, {{-1, Mnemonic::OR}}},
        {{Prefix::NONE, u2d("\x33")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::REXW, u2d("\x33")}, {{-1, Mnemonic::XOR}}},
        {{Prefix::P66, u2d("\x33")}, {{-1, Mnemonic::XOR}}},

        // MOV
        {{Prefix::NONE, u2d("\x88")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\x88")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::P66, u2d("\x89")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\x89")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\x89")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::NONE, u2d("\x8A")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\x8A")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::P66, u2d("\x8B")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\x8B")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\x8B")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::NONE, u2d("\x8C")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\x8C")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::NONE, u2d("\x8E")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\x8E")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::NONE, u2d("\xA0")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xA0")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::P66, u2d("\xA1")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xA1")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xA1")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::NONE, u2d("\xA2")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xA2")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::NONE, u2d("\xA3")}, {{-1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xA3")}, {{-1, Mnemonic::MOV}}},

        {{Prefix::NONE, u2d("\xB0")}, {{0, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB0")}, {{0, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB1")}, {{1, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB1")}, {{1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB2")}, {{2, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB2")}, {{2, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB3")}, {{3, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB3")}, {{3, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB4")}, {{4, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB4")}, {{4, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB5")}, {{5, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB5")}, {{5, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB6")}, {{6, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB6")}, {{6, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB7")}, {{7, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xB7")}, {{7, Mnemonic::MOV}}},

        {{Prefix::P66, u2d("\xB8")}, {{0, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB8")}, {{0, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xB8")}, {{0, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xB9")}, {{1, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xB9")}, {{1, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xB9")}, {{1, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xBA")}, {{2, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xBA")}, {{2, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xBA")}, {{2, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xBB")}, {{3, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xBB")}, {{3, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xBB")}, {{3, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xBC")}, {{4, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xBC")}, {{4, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xBC")}, {{4, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xBD")}, {{5, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xBD")}, {{5, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xBD")}, {{5, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xBE")}, {{6, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xBE")}, {{6, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xBE")}, {{6, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xBF")}, {{7, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xBF")}, {{7, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xBF")}, {{7, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xC6")}, {{0, Mnemonic::MOV}}},
        {{Prefix::REX, u2d("\xC6")}, {{0, Mnemonic::MOV}}},
        {{Prefix::P66, u2d("\xC7")}, {{0, Mnemonic::MOV}}},
        {{Prefix::NONE, u2d("\xC7")}, {{0, Mnemonic::MOV}}},
        {{Prefix::REXW, u2d("\xC7")}, {{0, Mnemonic::MOV}}},

        // NEG, NOT, MUL, IMUL, DIV, IDIV, TEST
        {{Prefix::NONE, u2d("\xF6")},
         {{3, Mnemonic::NEG},
          {2, Mnemonic::NOT},
          {4, Mnemonic::MUL},
          {5, Mnemonic::IMUL},
          {6, Mnemonic::DIV},
          {7, Mnemonic::IDIV},
          {0, Mnemonic::TEST}}},
        {{Prefix::REX, u2d("\xF6")},
         {{3, Mnemonic::NEG},
          {2, Mnemonic::NOT},
          {4, Mnemonic::MUL},
          {5, Mnemonic::IMUL},
          {6, Mnemonic::DIV},
          {7, Mnemonic::IDIV},
          {0, Mnemonic::TEST}}},

        {{Prefix::P66, u2d("\xF7")},
         {{2, Mnemonic::NOT},
          {4, Mnemonic::MUL},
          {5, Mnemonic::IMUL},
          {6, Mnemonic::DIV},
          {7, Mnemonic::IDIV},
          {0, Mnemonic::TEST}}},
        {{Prefix::NONE, u2d("\xF7")},
         {{3, Mnemonic::NEG},
          {2, Mnemonic::NOT},
          {4, Mnemonic::MUL},
          {5, Mnemonic::IMUL},
          {6, Mnemonic::DIV},
          {7, Mnemonic::IDIV},
          {0, Mnemonic::TEST}}},
        {{Prefix::REXW, u2d("\xF7")},
         {{3, Mnemonic::NEG},
          {2, Mnemonic::NOT},
          {4, Mnemonic::MUL},
          {5, Mnemonic::IMUL},
          {6, Mnemonic::DIV},
          {7, Mnemonic::IDIV},
          {0, Mnemonic::TEST}}},

        {{Prefix::P66, u2d("\x0F\xAF")}, {{-1, Mnemonic::IMUL}}},
        {{Prefix::NONE, u2d("\x0F\xAF")}, {{-1, Mnemonic::IMUL}}},
        {{Prefix::REXW, u2d("\x0F\xAF")}, {{-1, Mnemonic::IMUL}}},

        {{Prefix::P66, u2d("\x6B")}, {{-1, Mnemonic::IMUL}}},
        {{Prefix::NONE, u2d("\x6B")}, {{-1, Mnemonic::IMUL}}},
        {{Prefix::REXW, u2d("\x6B")}, {{-1, Mnemonic::IMUL}}},

        {{Prefix::P66, u2d("\x69")}, {{-1, Mnemonic::IMUL}}},
        {{Prefix::NONE, u2d("\x69")}, {{-1, Mnemonic::IMUL}}},
        {{Prefix::REXW, u2d("\x69")}, {{-1, Mnemonic::IMUL}}},

        {{Prefix::NONE, u2d("\xA8")}, {{-1, Mnemonic::TEST}}},
        {{Prefix::P66, u2d("\xA9")}, {{-1, Mnemonic::TEST}}},
        {{Prefix::NONE, u2d("\xA9")}, {{-1, Mnemonic::TEST}}},
        {{Prefix::REXW, u2d("\xA9")}, {{-1, Mnemonic::TEST}}},

        // INC, DEC
        {{Prefix::NONE, u2d("\xFE")}, {{0, Mnemonic::INC}, {1, Mnemonic::DEC}}},
        {{Prefix::REX, u2d("\xFE")}, {{0, Mnemonic::INC}, {1, Mnemonic::DEC}}},
        {{Prefix::REXW, u2d("\xFE")}, {{0, Mnemonic::INC}, {1, Mnemonic::DEC}}},

        // CBW, CWDE, CDQE
        {{Prefix::P66, u2d("\x98")}, {{-1, Mnemonic::CBW}}},
        {{Prefix::NONE, u2d("\x98")}, {{-1, Mnemonic::CWDE}}},
        {{Prefix::REXW, u2d("\x98")}, {{-1, Mnemonic::CDQE}}},

        // CWD, CDQ, CQO
        {{Prefix::P66, u2d("\x98")}, {{-1, Mnemonic::CWD}}},
        {{Prefix::NONE, u2d("\x98")}, {{-1, Mnemonic::CDQ}}},
        {{Prefix::REXW, u2d("\x98")}, {{-1, Mnemonic::CQO}}},

        // MOVSX
        {{Prefix::P66, u2d("\x0F\xBE")}, {{-1, Mnemonic::MOVSX}}},
        {{Prefix::NONE, u2d("\x0F\xBE")}, {{-1, Mnemonic::MOVSX}}},
        {{Prefix::REX, u2d("\x0F\xBE")}, {{-1, Mnemonic::MOVSX}}},
        {{Prefix::NONE, u2d("\x0F\xBF")}, {{-1, Mnemonic::MOVSX}}},
        {{Prefix::REXW, u2d("\x0F\xBF")}, {{-1, Mnemonic::MOVSX}}},

        // MOVSXD
        {{Prefix::REXW, u2d("\x63")}, {{-1, Mnemonic::MOVSXD}}},

        // MOVZX
        {{Prefix::P66, u2d("\x0F\xB6")}, {{-1, Mnemonic::MOVZX}}},
        {{Prefix::NONE, u2d("\x0F\xB6")}, {{-1, Mnemonic::MOVZX}}},
        {{Prefix::REX, u2d("\x0F\xB6")}, {{-1, Mnemonic::MOVZX}}},
        {{Prefix::NONE, u2d("\x0F\xB7")}, {{-1, Mnemonic::MOVZX}}},
        {{Prefix::REXW, u2d("\x0F\xB7")}, {{-1, Mnemonic::MOVZX}}},

        // LEA
        {{Prefix::P66, u2d("\x8D")}, {{-1, Mnemonic::LEA}}},
        {{Prefix::NONE, u2d("\x8D")}, {{-1, Mnemonic::LEA}}},
        {{Prefix::REXW, u2d("\x8D")}, {{-1, Mnemonic::LEA}}},

        // NOP
        {{Prefix::NONE, u2d("\x90")}, {{-1, Mnemonic::NOP}}},
        {{Prefix::NONE, u2d("\x0F\x1F")}, {{0, Mnemonic::NOP}}},

        // RET
        {{Prefix::NONE, u2d("\xC3")}, {{-1, Mnemonic::RET}}},
        {{Prefix::NONE, u2d("\xCB")}, {{-1, Mnemonic::RET}}},
        {{Prefix::NONE, u2d("\xC2")}, {{-1, Mnemonic::RET}}},
        {{Prefix::NONE, u2d("\xCA")}, {{-1, Mnemonic::RET}}},

        {{Prefix::NONE, u2d("\xFF")},
         {{0, Mnemonic::INC},
          {1, Mnemonic::DEC},
          {2, Mnemonic::CALL},
          {4, Mnemonic::JMP},
          {5, Mnemonic::JMP},
          {6, Mnemonic::PUSH}}},

        // CALL
        {{Prefix::NONE, u2d("\xE8")}, {{-1, Mnemonic::CALL}}},
        {{Prefix::NONE, u2d("\x9A")}, {{-1, Mnemonic::CALL}}},

        // JMP
        {{Prefix::NONE, u2d("\xEB")}, {{-1, Mnemonic::JMP}}},
        {{Prefix::NONE, u2d("\xE9")}, {{-1, Mnemonic::JMP}}},

        // POP
        {{Prefix::NONE, u2d("\x8F")}, {{0, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x58")}, {{0, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x59")}, {{1, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x5A")}, {{2, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x5B")}, {{3, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x5C")}, {{4, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x5D")}, {{5, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x5E")}, {{6, Mnemonic::POP}}},
        {{Prefix::NONE, u2d("\x5F")}, {{7, Mnemonic::POP}}},

        // PUSH
        {{Prefix::NONE, u2d("\x50")}, {{0, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x51")}, {{1, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x52")}, {{2, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x53")}, {{3, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x54")}, {{4, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x55")}, {{5, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x56")}, {{6, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x57")}, {{7, Mnemonic::PUSH}}},
        {{Prefix::NONE, u2d("\x68")}, {{-1, Mnemonic::PUSH}}},
};

// Lookup table for operand information
// (prefix, operator, opcode) -> (encoding, remaining opecodes, operands)
const std::unordered_map<
    std::tuple<Prefix, Mnemonic, int>,
    std::tuple<OpEnc, std::vector<std::string>, std::vector<Operand>>>
    OPERAND_LOOKUP = {
        // ADD
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x04")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x05")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x05")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::ADD, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x01")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x01")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x02")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::ADD, u2d("\x02")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::ADD, u2d("\x03")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::ADD, u2d("\x03")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // ADC
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x14")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x15")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x15")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::ADC, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x11")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x11")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x12")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::ADC, u2d("\x12")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::ADC, u2d("\x13")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::ADC, u2d("\x13")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // SUB
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x2C")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x2D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x2D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::SUB, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x29")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x29")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x2A")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::SUB, u2d("\x2A")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::SUB, u2d("\x2B")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::SUB, u2d("\x2B")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // SBB
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x1C")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x1D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x1D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::SBB, u2d("\x80")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x19")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x19")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x1A")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::SBB, u2d("\x1A")},
         {OpEnc::RM, {"ib"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::SBB, u2d("\x1B")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::SBB, u2d("\x1B")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // INC
        {{Prefix::NONE, Mnemonic::INC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm8}}},
        {{Prefix::REX, Mnemonic::INC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::INC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::INC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm64}}},

        // DEC
        {{Prefix::NONE, Mnemonic::DEC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm8}}},
        {{Prefix::REX, Mnemonic::DEC, u2d("\xFE")},
         {OpEnc::M, {}, {Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::DEC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::DEC, u2d("\xFF")},
         {OpEnc::M, {}, {Operand::rm64}}},

        // NEG
        {{Prefix::NONE, Mnemonic::NEG, u2d("\xF6")},
         {OpEnc::M, {}, {Operand::rm8}}},
        {{Prefix::REX, Mnemonic::NEG, u2d("\xF6")},
         {OpEnc::M, {}, {Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::NEG, u2d("\xF7")},
         {OpEnc::M, {}, {Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::NEG, u2d("\xF7")},
         {OpEnc::M, {}, {Operand::rm64}}},

        // AND
        {{Prefix::NONE, Mnemonic::AND, u2d("\x24")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x25")},
         {OpEnc::I, {"iw"}, {Operand::ax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x25")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x25")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm64, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x21")},
         {OpEnc::MR, {"/r"}, {Operand::rm16, Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x21")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x21")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::P66, Mnemonic::AND, u2d("\x23")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::AND, u2d("\x23")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::AND, u2d("\x23")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // OR
        {{Prefix::NONE, Mnemonic::OR, u2d("\x0C")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x0D")},
         {OpEnc::I, {"iw"}, {Operand::ax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x0D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x0D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm64, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x09")},
         {OpEnc::MR, {"/r"}, {Operand::rm16, Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x09")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x09")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::P66, Mnemonic::OR, u2d("\x0B")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::OR, u2d("\x0B")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::OR, u2d("\x0B")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // XOR
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x34")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x35")},
         {OpEnc::I, {"iw"}, {Operand::ax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x35")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x35")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x31")},
         {OpEnc::MR, {"/r"}, {Operand::rm16, Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x31")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x31")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::P66, Mnemonic::XOR, u2d("\x33")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::XOR, u2d("\x33")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::XOR, u2d("\x33")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // NOT
        {{Prefix::NONE, Mnemonic::NOT, u2d("\xF6")},
         {OpEnc::RM, {}, {Operand::reg8}}},
        {{Prefix::REX, Mnemonic::NOT, u2d("\xF6")},
         {OpEnc::RM, {}, {Operand::reg8}}},
        {{Prefix::P66, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg64}}},

        // MUL
        {{Prefix::NONE, Mnemonic::NOT, u2d("\xF6")},
         {OpEnc::RM, {}, {Operand::reg8}}},
        {{Prefix::REX, Mnemonic::NOT, u2d("\xF6")},
         {OpEnc::RM, {}, {Operand::reg8}}},
        {{Prefix::P66, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::NOT, u2d("\xF7")},
         {OpEnc::RM, {}, {Operand::reg64}}},

        // IMUL
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\xF6")},
         {OpEnc::MR, {"/r"}, {Operand::rm8}}},
        {{Prefix::REX, Mnemonic::IMUL, u2d("\xF6")},
         {OpEnc::MR, {"/r"}, {Operand::rm8}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\xF7")},
         {OpEnc::MR, {"/r"}, {Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\xF7")},
         {OpEnc::MR, {"/r"}, {Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\xF7")},
         {OpEnc::MR, {"/r"}, {Operand::rm64}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\x0F\xAF")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x0F\xAF")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x0F\xAF")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg16, Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg32, Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg64, Operand::rm64, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x6B")},
         {OpEnc::RMI, {"ib"}, {Operand::reg64, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"iw"}, {Operand::reg16, Operand::rm16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"id"}, {Operand::reg32, Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"id"}, {Operand::reg64, Operand::rm64, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"iw"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"id"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::IMUL, u2d("\x69")},
         {OpEnc::RMI, {"id"}, {Operand::reg64, Operand::imm32}}},

        // DIV
        {{Prefix::NONE, Mnemonic::DIV, u2d("\xF6")},
         {OpEnc::M, {"/r"}, {Operand::rm8}}},
        {{Prefix::REX, Mnemonic::DIV, u2d("\xF6")},
         {OpEnc::M, {"/r"}, {Operand::rm8}}},
        {{Prefix::P66, Mnemonic::DIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::DIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::DIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm64}}},

        // IDIV
        {{Prefix::NONE, Mnemonic::IDIV, u2d("\xF6")},
         {OpEnc::M, {"/r"}, {Operand::rm8}}},
        {{Prefix::REX, Mnemonic::IDIV, u2d("\xF6")},
         {OpEnc::M, {"/r"}, {Operand::rm8}}},
        {{Prefix::P66, Mnemonic::IDIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::IDIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::IDIV, u2d("\xF7")},
         {OpEnc::M, {"/r"}, {Operand::rm64}}},

        // CMP
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x3C")},
         {OpEnc::I, {"id"}, {Operand::al, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::CMP, u2d("\x3D")},
         {OpEnc::I, {"id"}, {Operand::ax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x3D")},
         {OpEnc::I, {"id"}, {Operand::eax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x3D")},
         {OpEnc::I, {"id"}, {Operand::rax, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::CMP, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x81")},
         {OpEnc::MI, {"id"}, {Operand::rm64, Operand::imm32}}},
        {{Prefix::P66, Mnemonic::CMP, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm16, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm32, Operand::imm8}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x83")},
         {OpEnc::MI, {"ib"}, {Operand::rm64, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::CMP, u2d("\x39")},
         {OpEnc::MR, {"/r"}, {Operand::rm16, Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x39")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x39")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::P66, Mnemonic::CMP, u2d("\x3B")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x3A")},
         {OpEnc::RM, {"/r"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::CMP, u2d("\x3A")},
         {OpEnc::RM, {"/r"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::CMP, u2d("\x3B")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::CMP, u2d("\x3B")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // TEST
        {{Prefix::NONE, Mnemonic::TEST, u2d("\xA8")},
         {OpEnc::I, {"ib"}, {Operand::al, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::TEST, u2d("\xA9")},
         {OpEnc::I, {"iw"}, {Operand::ax, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\xA9")},
         {OpEnc::I, {"id"}, {Operand::ax, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::TEST, u2d("\xA9")},
         {OpEnc::I, {"id"}, {Operand::ax, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\xF6")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::TEST, u2d("\xF6")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::TEST, u2d("\xF7")},
         {OpEnc::MI, {"iw"}, {Operand::rm16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\xF7")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::TEST, u2d("\xF7")},
         {OpEnc::MI, {"id"}, {Operand::rm64, Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\x84")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::REX, Mnemonic::TEST, u2d("\x84")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::P66, Mnemonic::TEST, u2d("\x85")},
         {OpEnc::MR, {"/r"}, {Operand::rm16, Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::TEST, u2d("\x85")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::TEST, u2d("\x85")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},

        // MOV
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x88")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\x88")},
         {OpEnc::MR, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\x89")},
         {OpEnc::MR, {"/r"}, {Operand::rm16, Operand::reg16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x89")},
         {OpEnc::MR, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\x89")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x8A")},
         {OpEnc::RM, {"/r"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\x8A")},
         {OpEnc::RM, {"/r"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\x8B")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x8B")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\x8B")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x8C")},
         {OpEnc::MR, {"/r"}, {Operand::rm16, Operand::sreg}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\x8C")},
         {OpEnc::MR, {"/r"}, {Operand::rm64, Operand::sreg}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\x8E")},
         {OpEnc::RM, {"/r"}, {Operand::sreg, Operand::rm16}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\x8E")},
         {OpEnc::RM, {"/r"}, {Operand::sreg, Operand::rm64}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xA0")},
         {OpEnc::FD, {}, {Operand::al, Operand::moffs8}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xA0")},
         {OpEnc::FD, {}, {Operand::al, Operand::moffs8}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xA1")},
         {OpEnc::FD, {}, {Operand::ax, Operand::moffs16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xA1")},
         {OpEnc::FD, {}, {Operand::eax, Operand::moffs32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xA1")},
         {OpEnc::FD, {}, {Operand::rax, Operand::moffs64}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xA2")},
         {OpEnc::TD, {}, {Operand::moffs8, Operand::al}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xA2")},
         {OpEnc::TD, {}, {Operand::moffs8, Operand::al}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xA3")},
         {OpEnc::TD, {}, {Operand::moffs16, Operand::ax}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xA3")},
         {OpEnc::TD, {}, {Operand::moffs64, Operand::rax}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB0")},
         {OpEnc::OI, {"0"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB0")},
         {OpEnc::OI, {"0"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB1")},
         {OpEnc::OI, {"1"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB1")},
         {OpEnc::OI, {"1"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB2")},
         {OpEnc::OI, {"2"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB2")},
         {OpEnc::OI, {"2"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB3")},
         {OpEnc::OI, {"3"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB3")},
         {OpEnc::OI, {"3"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB4")},
         {OpEnc::OI, {"4"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB4")},
         {OpEnc::OI, {"4"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB5")},
         {OpEnc::OI, {"5"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB5")},
         {OpEnc::OI, {"5"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB6")},
         {OpEnc::OI, {"6"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB6")},
         {OpEnc::OI, {"6"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB7")},
         {OpEnc::OI, {"7"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xB7")},
         {OpEnc::OI, {"7"}, {Operand::reg8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xB8")},
         {OpEnc::OI, {"0"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB8")},
         {OpEnc::OI, {"0"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xB8")},
         {OpEnc::OI, {"0"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xB9")},
         {OpEnc::OI, {"1"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xB9")},
         {OpEnc::OI, {"1"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xB9")},
         {OpEnc::OI, {"1"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBA")},
         {OpEnc::OI, {"2"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBA")},
         {OpEnc::OI, {"2"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBA")},
         {OpEnc::OI, {"2"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBB")},
         {OpEnc::OI, {"3"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBB")},
         {OpEnc::OI, {"3"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBB")},
         {OpEnc::OI, {"3"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBC")},
         {OpEnc::OI, {"4"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBC")},
         {OpEnc::OI, {"4"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBC")},
         {OpEnc::OI, {"4"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBD")},
         {OpEnc::OI, {"5"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBD")},
         {OpEnc::OI, {"5"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBD")},
         {OpEnc::OI, {"5"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBE")},
         {OpEnc::OI, {"6"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBE")},
         {OpEnc::OI, {"6"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBE")},
         {OpEnc::OI, {"6"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xBF")},
         {OpEnc::OI, {"7"}, {Operand::reg16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xBF")},
         {OpEnc::OI, {"7"}, {Operand::reg32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xBF")},
         {OpEnc::OI, {"7"}, {Operand::reg64, Operand::imm64}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xC6")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::REX, Mnemonic::MOV, u2d("\xC6")},
         {OpEnc::MI, {"ib"}, {Operand::rm8, Operand::imm8}}},
        {{Prefix::P66, Mnemonic::MOV, u2d("\xC7")},
         {OpEnc::MI, {"iw"}, {Operand::rm16, Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::MOV, u2d("\xC7")},
         {OpEnc::MI, {"id"}, {Operand::rm32, Operand::imm32}}},
        {{Prefix::REXW, Mnemonic::MOV, u2d("\xC7")},
         {OpEnc::MI, {"id"}, {Operand::rm64, Operand::imm32}}},

        // CBW
        {{Prefix::P66, Mnemonic::CBW, u2d("\x98")}, {OpEnc::NP, {}, {}}},

        // CWDE
        {{Prefix::NONE, Mnemonic::CWDE, u2d("\x98")}, {OpEnc::NP, {}, {}}},

        // CDQE
        {{Prefix::REXW, Mnemonic::CDQE, u2d("\x98")}, {OpEnc::NP, {}, {}}},

        // CWD
        {{Prefix::P66, Mnemonic::CWD, u2d("\x99")}, {OpEnc::NP, {}, {}}},

        // CDQ
        {{Prefix::NONE, Mnemonic::CDQ, u2d("\x99")}, {OpEnc::NP, {}, {}}},

        // CQO
        {{Prefix::REXW, Mnemonic::CQO, u2d("\x99")}, {OpEnc::NP, {}, {}}},

        // MOVSX
        {{Prefix::P66, Mnemonic::MOVSX, u2d("\x0F\xBE")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::MOVSX, u2d("\x0F\xBE")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::MOVSX, u2d("\x0F\xBE")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::MOVSX, u2d("\x0F\xBF")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm16}}},
        {{Prefix::REXW, Mnemonic::MOVSX, u2d("\x0F\xBF")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm16}}},
        {{Prefix::P66, Mnemonic::MOVZX, u2d("\x0F\xB6")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::MOVZX, u2d("\x0F\xB6")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm8}}},
        {{Prefix::REX, Mnemonic::MOVZX, u2d("\x0F\xB6")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm8}}},
        {{Prefix::NONE, Mnemonic::MOVZX, u2d("\x0F\xB7")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm16}}},
        {{Prefix::REXW, Mnemonic::MOVZX, u2d("\x0F\xB7")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm32}}},

        // MOVSXD
        {{Prefix::REXW, Mnemonic::MOVSXD, u2d("\x63")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm32}}},

        // LEA
        {{Prefix::P66, Mnemonic::LEA, u2d("\x8D")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::m}}},
        {{Prefix::NONE, Mnemonic::LEA, u2d("\x8D")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::m}}},
        {{Prefix::REXW, Mnemonic::LEA, u2d("\x8D")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::m}}},

        /*
        // BSWAP
        {{Prefix::NONE, Mnemonic::BSWAP, u2d("\x0F\xC8"), Opcode_plus_rd()},
         {OpEnc::NP, {"rd"}, {Operand::reg32}}},
        {{Prefix::REXW, Mnemonic::BSWAP, u2d("\x0F\xC8"), Opcode_plus_rd()},
         {OpEnc::NP, {"rd"}, {Operand::reg64}}},

        // XCHG AX, r16
        {{Prefix::P66, Mnemonic::XCHG, u2d("\x90"), Opcode_plus_rw()},
         {OpEnc::NP, {"rw"}, {Operand::ax, Operand::reg16}}},
        {{Prefix::P66, Mnemonic::XCHG, u2d("\x90"), Opcode_plus_rw()},
         {OpEnc::NP, {"rw"}, {Operand::reg16, Operand::ax}}},
        {{Prefix::NONE, Mnemonic::XCHG, u2d("\x90"), Opcode_plus_rd()},
         {OpEnc::NP, {"rd"}, {Operand::eax, Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::XCHG, u2d("\x90"), Opcode_plus_rd()},
         {OpEnc::NP, {"rd"}, {Operand::reg32, Operand::eax}}},
        {{Prefix::REXW, Mnemonic::XCHG, u2d("\x90"), Opcode_plus_rd()},
         {OpEnc::NP, {"rd"}, {Operand::rax, Operand::reg64}}},
        {{Prefix::REXW, Mnemonic::XCHG, u2d("\x90"), Opcode_plus_rd()},
         {OpEnc::NP, {"rd"}, {Operand::reg64, Operand::rax}}},
        */

        {{Prefix::NONE, Mnemonic::XCHG, u2d("\x86")},
         {OpEnc::RM, {"/r"}, {Operand::rm8, Operand::reg8}}},
        {{Prefix::NONE, Mnemonic::XCHG, u2d("\x86")},
         {OpEnc::RM, {"/r"}, {Operand::reg8, Operand::rm8}}},
        {{Prefix::P66, Mnemonic::XCHG, u2d("\x87")},
         {OpEnc::RM, {"/r"}, {Operand::rm16, Operand::reg16}}},
        {{Prefix::P66, Mnemonic::XCHG, u2d("\x87")},
         {OpEnc::RM, {"/r"}, {Operand::reg16, Operand::rm16}}},
        {{Prefix::NONE, Mnemonic::XCHG, u2d("\x87")},
         {OpEnc::RM, {"/r"}, {Operand::rm32, Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::XCHG, u2d("\x87")},
         {OpEnc::RM, {"/r"}, {Operand::reg32, Operand::rm32}}},
        {{Prefix::REXW, Mnemonic::XCHG, u2d("\x87")},
         {OpEnc::RM, {"/r"}, {Operand::rm64, Operand::reg64}}},
        {{Prefix::REXW, Mnemonic::XCHG, u2d("\x87")},
         {OpEnc::RM, {"/r"}, {Operand::reg64, Operand::rm64}}},

        // NOP
        {{Prefix::NONE, Mnemonic::NOP, u2d("\x90")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::NOP, u2d("\x0F\x1F")},
         {OpEnc::M, {"0"}, {Operand::rm32}}},

        // RET
        {{Prefix::NONE, Mnemonic::RET, u2d("\xC3")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::RET, u2d("\xCB")}, {OpEnc::NP, {}, {}}},
        {{Prefix::NONE, Mnemonic::RET, u2d("\xC2")},
         {OpEnc::I, {"iw"}, {Operand::imm16}}},
        {{Prefix::NONE, Mnemonic::RET, u2d("\xCA")},
         {OpEnc::I, {"iw"}, {Operand::imm16}}},

        // CALL
        {{Prefix::NONE, Mnemonic::CALL, u2d("\xE8")},
         {OpEnc::D, {}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::CALL, u2d("\xFF")},
         {OpEnc::D, {"2"}, {Operand::rm64}}},

        // JZ
        {{Prefix::NONE, Mnemonic::JZ, u2d("\x0F\x84")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JZ, u2d("\x74")},
         {OpEnc::D, {"cd"}, {Operand::imm8}}},

        // JNZ
        {{Prefix::NONE, Mnemonic::JNZ, u2d("\x0F\x85")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JNZ, u2d("\x75")},
         {OpEnc::D, {"cd"}, {Operand::imm8}}},

        // JMP
        {{Prefix::NONE, Mnemonic::JMP, u2d("\xEB")},
         {OpEnc::D, {"cd"}, {Operand::imm8}}},
        {{Prefix::NONE, Mnemonic::JMP, u2d("\xE9")},
         {OpEnc::D, {"cd"}, {Operand::imm32}}},
        {{Prefix::NONE, Mnemonic::JMP, u2d("\xFF")},
         {OpEnc::M, {"4"}, {Operand::rm64}}},

        // POP
        {{Prefix::NONE, Mnemonic::POP, u2d("\x8F")},
         {OpEnc::M, {"0"}, {Operand::rm64}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x58")},
         {OpEnc::O, {"0"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x59")},
         {OpEnc::O, {"1"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x5A")},
         {OpEnc::O, {"2"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x5B")},
         {OpEnc::O, {"3"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x5C")},
         {OpEnc::O, {"4"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x5D")},
         {OpEnc::O, {"5"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x5E")},
         {OpEnc::O, {"6"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::POP, u2d("\x5F")},
         {OpEnc::O, {"7"}, {Operand::reg32}}},

        // PUSH
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\xFF")},
         {OpEnc::M, {"6"}, {Operand::rm32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x50")},
         {OpEnc::O, {"0"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x51")},
         {OpEnc::O, {"1"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x52")},
         {OpEnc::O, {"2"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x53")},
         {OpEnc::O, {"3"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x54")},
         {OpEnc::O, {"4"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x55")},
         {OpEnc::O, {"5"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x56")},
         {OpEnc::O, {"6"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x57")},
         {OpEnc::O, {"7"}, {Operand::reg32}}},
        {{Prefix::NONE, Mnemonic::PUSH, u2d("\x68")},
         {OpEnc::I, {"id"}, {Operand::imm32}}},
};

// Supported operators set
const std::unordered_set<std::string> SUPPORTED_OPERATORS;
